### ISSUE TITLE
Add CNAME to S3 bucket

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#100]
We're imagining wanting to do this before serving assets directly from S3, to avoid people being confused by seeing an AWS URL.

**Comment by floehopper** [comment]
I might be wrong, but it looks as if we should be able to add the `CNAME` DNS record to the YAML file(s) in [govuk-dns-config][1] which are applied using [govuk-dns][2]. It looks as if the latter uses Terraform, but it's not clear to me how it relates to [govuk-terraform-provisioning][3], i.e. does it share Terraform state on S3?

[1]: https://github.com/alphagov/govuk-dns-config
[2]: https://github.com/alphagov/govuk-dns
[3]: https://github.com/alphagov/govuk-terraform-provisioning

**Comment by floehopper** [comment]
We're now actively investigating [an alternative approach](https://github.com/alphagov/asset-manager/milestone/4). Closing.
