### ISSUE TITLE
Make S3 bucket public in integration

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#101]
We'll need to do this in order to serve assets directly from S3.

**Comment by floehopper** [comment]
I think this is simply a matter of changing the [`acl` argument on the bucket][1] from "private" to "public-read". See the documentation for [Terraform's `aws_s3_bucket` resource][2] and [S3 canned ACLs][3].

[1]: https://github.com/alphagov/govuk-terraform-provisioning/blob/4b49c06d05674ade16e9d5119991b6f0ac6030df/projects/asset-manager/resources/buckets.tf#L3
[2]: https://www.terraform.io/docs/providers/aws/r/s3_bucket.html
[3]: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by floehopper** [comment]
See https://github.com/alphagov/govuk-terraform-provisioning/pull/128.

**Comment by chrisroos** [comment]
We've made and merged the necessary change in https://github.com/alphagov/govuk-terraform-provisioning/pull/130. We're currently waiting for this change to be deployed to integration.

**Comment by chrisroos** [comment]
The changes in https://github.com/alphagov/govuk-terraform-provisioning/pull/130 have now been deployed to integration.

I've tested that the change is working as expected by uploading an attachment to a Manual Section (in Manuals Publisher) and requesting the uploaded asset with the `redirect_to_s3=true` querystring.

**Comment by floehopper** [comment]
Based on @chrisroos' last comment, I'm closing this issue. @chrisroos: Please re-open if you think we've missed anything.
