### ISSUE TITLE
Document the destroy and restore API endpoints in the README

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#106]
I can only imagine that it's an oversight that the rest of the API is documented but these aren't.

**Comment by floehopper** [comment]
FWIW the [delete & restore methods are documented][1] in the `gds-api-adapters` gem.

[1]: https://github.com/alphagov/gds-api-adapters/blob/6984336dc73d07a44d409ba138ae7e10d83148d2/lib/gds_api/asset_manager.rb#L94-L138

**Comment by chrisroos** [comment]
I've updated the README in PR #123.

**Comment by floehopper** [comment]
@chrisroos: I'm closing this given that #123 has been merged. Please re-open if I've missed something.
