### ISSUE TITLE
Log Delayed Job output in all environments

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#114]
It would be useful if the `delayed_job` logs were available through Kibana so we can see how long virus checking and s3 uploading is taking, and trace any errors. 

I asked in slack and @tuzz said: 

> It doesn't look like they are. On `backend-1.integration` I can see `/var/log/asset-manager/delayed_job.out.log` but there's no JSON version of this.
>
> A kibana query of `@fields.application:asset-manager` shows all logs for that application, but that only appears to be http requests.

So it looks like we might have to format the logs as JSON and then configure something to forward them to Kibana.

**Comment by floehopper** [comment]
This might be rendered moot if we [use Sidekiq instead of Delayed Job](https://github.com/alphagov/asset-manager/issues/179).

**Comment by chrislo** [comment]
It has indeed. We switched to sidekiq in #179 so this issue is no longer relevant.
