### ISSUE TITLE
Test behaviour of Asset Manager clients when redirecting to S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#119]
We want to test the behaviour on the Asset Manager clients of redirecting to assets on S3. This will help give us confidence that it's OK to deploy these changes to staging and production.

## Dependencies

- [x] Making S3 bucket publicly readable as per PR #101
- [x] Deploying the branch in PR #120 to integration

## Client apps of Asset Manager

* Specialist Publisher
  * Assets are attached to Documents
* Manuals Publisher
  * Assets are attached to Sections
  * Example of a section containing a linked and embedded attachment - https://www.gov.uk/guidance/the-highway-code/vehicle-markings
* Service Manual
  * Assets are uploaded by dragging and dropping them into the text area of a "page"
* Travel Advice Publisher
  * A single map attachment can be uploaded to a location
  * A single PDF attachment can be uploaded to a location
* Publisher
  * Assets can be uploaded to Campaigns (which is a retired format)
  * Assets can be uploaded to Videos (which is a retired format)

**Comment by chrisroos** [comment]
@chrislo and I have tested the behaviour of redirecting assets to S3 in integration. We did this by deploying the branch from PR #120 and creating one of each of a Manual, Specialist Publisher document, Service Manual guide and updating a country within the Travel Advice Publisher:

This is what we did in each case:

* Specialist Publisher
  * Create an AAIB report
  * Attach a PDF and an image to the AAIB report
  * Embed the image in the body of the report
  * Add a link to the PDF in the body of the AAIB report

* Manuals Publisher
  * Create a manual with a single section
  * Attach a PDF and an image to the section
  * Embed the image in the body of the section
  * Add a link to the PDF in the body of the section

* Service Manual
  * Create a Guide
  * Upload an image attachment to the body of the Guide

* Travel Advice Publisher
  * Edit "Afghanistan"
  * Replace the map image with an alternative map image
  * Replace the map PDF with an alternative map PDF

In all cases, the HTML generated remains the same, i.e. the URLs have the form `https://assets-origin.integration.publishing.service.gov.uk/media/598c4840ed915d0375d9405f/the-highway-code-vehicle-markings.pdf`.

## Embedded images

* HTML remains the same.
* The browser follows the redirect in order to render the image in the page.
* User only sees new URL if they follow a link to the image directly (e.g. right click and "Open image in new tab") and they're redirected to the new URL.
* Responding with 307 tells machines to continue using the Asset Manager URL to request the image.

## Linked PDFs

* HTML remains the same.
* User sees the URL in the browser when they follow the link to the PDF (see screenshot below).
* Responding with 307 tells machines to continue using the Asset Manager URL to request the image.

![screenshot 2017-08-10 14 46 46](https://user-images.githubusercontent.com/6556/29173316-cabb9976-7dda-11e7-8f74-52311533dd6d.png)

**Comment by floehopper** [comment]
Based on @chrisroos' last comment, I've checked the remaining box in the PR description and I'm going to close this issue. @chrisroos: Please re-open if you think we've missed anything.
