### ISSUE TITLE
Configure nginx to proxy requests to assets on S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#127]
We've trialled this using a version of Asset Manager on EC2 and now want to make the change so that we can try the same thing within the GOV.UK environment.

We'll need to configure nginx to proxy requests for assets to S3. We'll need to add something like [this config for the `cloud-storage-proxy` location][nginx-location] to the asset-manager nginx config in govuk-puppet.

We should work out how much space we might be able to allow for the cache - I think the example above gives it 10GB.

[nginx-location]: https://gist.github.com/chrisroos/bf9e60642395c84e76cb0ecc1cd1272d#file-asset-manager-ec2-gov-uk-L66

**Comment by floehopper** [comment]
@chrisroos: Given that I believe that you & @chrislo are currently working on this, I'm assigning it to you.

**Comment by chrisroos** [comment]
We've opened https://github.com/alphagov/govuk-puppet/pull/6280 to configure nginx to proxy requests to assets on S3.

**Comment by chrisroos** [comment]
PR https://github.com/alphagov/govuk-puppet/pull/6280 has now been merged and should be automatically deployed to integration soon.

Closing.
