### ISSUE TITLE
Avoid sending S3 errors to the client

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#139]
In the proxying-to-S3 approach it's possible for errors from S3 to be sent to the client. I guess we'll want to send custom error messages if/when we enable this in production by default.

An illustration of the problem:

```
# Create temporary file
$ echo `date` > tmp.txt

# Upload file to asset-manager
$ curl http://asset-manager.dev.gov.uk/assets --form "asset[file]=@tmp.txt"

# Request file from S3 via nginx
$ curl "http://asset-manager.dev.gov.uk/media/5995b518759b7443e960b9b0/tmp.txt?proxy_via_nginx=true"
Thu Aug 17 15:22:25 UTC 2017

# Manually remove the file from S3 - to simulate the sort of problem we might encounter

# Request the file from S3 via nginx
$ curl "http://asset-manager.dev.gov.uk/media/5995b518759b7443e960b9b0/tmp.txt?proxy_via_nginx=true"
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>5995b518759b7443e960b9b0</Key><RequestId>5B19547BA6F8A875</RequestId><HostId>5ZkLa2PeoC4B2TzsK93fsJ7VK8c5eR/CSMmzmnuc01IBy53N392vTDZwvkvKwAcYq994bcQeQoU=</HostId></Error>
```

**Comment by floehopper** [comment]
@chrisroos:

Presumably what we care about here is what the end user sees in production. Is that right? Your example uses a URL directly on the `asset-manager.dev.gov.uk` host, but I don't think that's representative of an end-user request and thus I'm not sure the response is very relevant.

It's also worth noting that the current behaviour is to return a 404 Not Found with a JSON body as follows:

```
$ curl -s -v "http://asset-manager.dev.gov.uk/media/599ef676759b7414919c2e7b/foo.txt"
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/599ef676759b7414919c2e7b/foo.txt HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Tue, 29 Aug 2017 09:22:24 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 41
< Connection: close
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache
< X-Request-Id: 218229e5-62c4-4132-a7db-4b28affb28d9
< X-Runtime: 0.007605
<
* Closing connection 0
{"_response_info":{"status":"not found"}}
```

**Comment by floehopper** [comment]
[It looks as if a bunch of error statuses are handled in the router](https://github.com/alphagov/govuk-puppet/blob/939b0aed1099557462a5e240cdca5f9ac98bb5e4/modules/router/templates/router_include.conf.erb#L79-L85). I need to remind myself whether or not asset requests pass through this Nginx instance.

**Comment by chrisroos** [comment]
You can see an example of the problem by requesting an asset in production that hasn't yet been uploaded to S3:

```
# Requesting it normally
$ curl "https://assets.publishing.service.gov.uk/media/55bb5ed1ed915d1565000002/across-carriageway-stop-line-signals-or-police.jpg" -v > /dev/null
< HTTP/1.1 200 OK

# Requesting it from S3
$ curl "https://assets.publishing.service.gov.uk/media/55bb5ed1ed915d1565000002/across-carriageway-stop-line-signals-or-police.jpg?proxy_via_nginx=true" -v > /dev/null
< HTTP/1.1 403 Forbidden
```

**Comment by chrisroos** [comment]
I've created issue #176 to investigate responding with a 404 when assets don't exist on S3.

**Comment by chrisroos** [comment]
@chrislo, @floehopper and I discussed this earlier today. We agreed that it doesn't really make sense to do anything about this given that we don't currently have friendly error pages for assets anyway. I've created issue #178 to capture the problem of unfriendly error pages and am therefore happy to close this issue.
