### ISSUE TITLE
Ensure Etag from nginx+s3proxy matches Etag from nginx+Sendfile

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#144]
We're imaging an incremental rollout of the nginx+s3proxy approach to serving assets. The same asset served from the two approaches currently has a different Etag. The Etag generated by nginx appears to be ([according to this Serverfault answer][serverfault-nginx-etag]) a combination of last modified date and content length. The Etag generated by S3 [may or may not be an md5 digest of the content depending on how the object was created and how it's encrypted][s3-etag].

The same asset having different Etags (e.g. etag-1 and etag-2) will result in some additional load on the asset-manager servers because a conditional GET using etag-1 might end up with a 200 response and etag-2, instead of a 304 response for etag-1.

I can think of two options (there may be others):

1. Generate the same Etags that nginx currently generates and store them against the objects in S3

    * This assumes that we can set an Etag on S3 and have it sent in the response to the client.
    * The advantage is that Etags remain the same and so caches can be informed that they can continue using a previously cached version of the file
    * The problem might be in generating the Etag value the same as nginx

2. Change the Etags for the current Sendfile mechanism and then use those same Etags when serving files from S3

    * This assumes we can customise the Etag sent from nginx (maybe by setting it in the Rails app) and that we can customise the Etag sent from S3
    * The disadvantage is that all cached content will/might have to be re-populated because the Etags have changed. If we're going to do this then we should roll it out in nginx and give it at least 24 hours to ensure all caches should have picked up the new Etags.
    * The advantage is that we're not tied to the Etag implementation of nginx.

[s3-etag]: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html
[serverfault-nginx-etag]: https://serverfault.com/questions/690341/algorithm-behind-nginx-etag-generation

**Comment by chrisroos** [comment]
There is a similar issue for making sure the Last-Modified values are the same in #148.

**Comment by floehopper** [comment]
As far as we can see in the [AWS SDK documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html) there's no way to *set* the value of the ETag or Last-Modified response headers for an S3 Object. We think this rules out option 1.

**Comment by floehopper** [comment]
It might be possible for the Rails app to generate an ETag and somehow instruct Nginx to replace the ETag response header which comes back from S3, but it's not at all obvious how we would do that.

**Comment by chrisroos** [comment]
> It might be possible for the Rails app to generate an ETag and somehow instruct Nginx to replace the ETag response header which comes back from S3, but it's not at all obvious how we would do that.

You should be able to strip the Etag response header from S3 by using `proxy_hide_header` (e.g. [as we've done to remove `x-amz-version-id`](https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/apps/asset_manager.pp#L127)). That might even be enough for an Etag response header from Rails to make its way back to the client. If it's not then we should be able to read an Etag header from Rails and manually set that in the response.

**Comment by floehopper** [comment]
We've spiked on a solution to this issue & #148 - a summary is record in [this gist](https://gist.github.com/floehopper/4b52c39cff18e108962c793c579dee1a).

**Comment by floehopper** [comment]
We want to check this is deployed to integration and check that it's working.

**Comment by floehopper** [comment]
> We want to check this is deployed to integration and check that it's working.

I think @chrisroos effectively tested this in his testing of #164. For example, you can see that the `ETag` header is the same whether Nginx serves the file from NFS or proxies it to S3 in the `curl` output in [this comment](https://github.com/alphagov/asset-manager/pull/164#issuecomment-325951294).

Closing.
