### ISSUE TITLE
Regularly copy assets from Production to Staging and Integration

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#145]
This is on the assumption that we currently regularly copy production assets to staging and integration. We should validate this assumption before doing any work on this.

**Comment by floehopper** [comment]
We think we only need this when stop saving assets to NFS.

**Comment by chrisroos** [comment]
I wonder whether we might need to do this before we start serving a percentage of asset requests by proxying to S3 in integration or staging... If we don't copy the assets between the S3 environments (i.e. production to staging and integration) then the database in integration/staging won't be in sync with the assets on S3 after the nightly database copy. If the database and S3 are out of sync then any requests served by proxying to S3 will fail.

I think we can also avoid this problem by ensuring that we don't serve any asset requests by proxying to S3 in integration or staging.

@chrislo / @floehopper: What do you think we should do about this? Should we prioritise copying the assets between S3 buckets? Or just keep the option disabled in integration/staging in the short term?

**Comment by chrislo** [comment]
I *think* that the production databases for the publishing applications also get copied over nightly - so in the case of manuals publisher on integration, it will have asset urls that point to the production assets for any assets added yesterday - I think that will continue to work when we switch to proxying to S3. Any newly uploaded assets in integration will be added to the integration bucket and will work as normal. Is that what you mean @chrisroos?

**Comment by chrisroos** [comment]
Aha, you're quite right @chrislo. I'd forgotten that we mostly/always(?) store asset URLs in content rather than an identifier that needs to be resolved by the asset-manager API. I think I'm happy that this isn't as much of a problem as I'd imagined.

**Comment by floehopper** [comment]
The other day we worked out that this is in fact an issue for *Whitehall* assets, because (at least some of) the URLs of existing assets are generated in the Rails app (rather than being embedded in content in the Content Store) and are therefore potentially environment-specific. This implies that we do need to setup syncing between production and staging/integration before we can remove the files on NFS corresponding to Whitehall assets within Asset Manager.

**Comment by floehopper** [comment]
I've opened the following PRs to implement this:

1. https://github.com/alphagov/govuk-terraform-provisioning/pull/143
2. https://github.com/alphagov/govuk-puppet/pull/6763
3. https://github.com/alphagov/env-sync-and-backup/pull/34

Note that 1 & 2 need to be merged and applied/deployed before 3 can be merged and deployed.

**Comment by floehopper** [comment]
I've just merged https://github.com/alphagov/govuk-puppet/pull/6763.

**Comment by floehopper** [comment]
https://github.com/alphagov/govuk-puppet/pull/6763 has been [automatically deployed to integration](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Puppet/3278/) and ought to be applied on all integration machines within 30 mins. However, it ought not to have any effect in any environment other than production.

**Comment by floehopper** [comment]
`govuk_puppet` seems to have run without incident on `asset-master-1.backend.integration`:

```
Nov  9 15:23:57 asset-master-1.backend puppet-agent[14159]: Finished catalog run in 15.59 seconds
```

**Comment by chrisroos** [comment]
Laura has applied our terraform changes in all environments. Note that we had to apply them in production first as the `govuk-assets-production-env-sync-user` user had to exist before we could grant it access to the buckets in integration and staging. Laura has also created credentials for this user and added them to secrets in https://github.com/alphagov/govuk-secrets/pull/109.

**Comment by chrisroos** [comment]
I've now merged https://github.com/alphagov/env-sync-and-backup/pull/34. @sihugh has confirmed that this doesn't need to be deployed so it should hopefully start syncing assets overnight tonight!

**Comment by chrisroos** [comment]
@emmabeynon helped me confirm that the AWS credentials in the asset-env-sync pseudo-app are working correctly.

We copied a file from the production bucket to the staging and integration buckets. The file already existed in integration but copying it successfully overwrote the file that was there.

```
# List the asset in integration
$ aws s3 ls s3://govuk-assets-integration/cadfad06-b44e-45ee-8ffd-61da0c4e24c8
2017-09-05 13:37:53      91139 cadfad06-b44e-45ee-8ffd-61da0c4e24c8

# Copy the asset from production to staging and integration
$ govuk_setenv asset-env-sync aws s3 cp s3://govuk-assets-production/cadfad06-b44e-45ee-8ffd-61da0c4e24c8 s3://govuk-assets-staging/
$ govuk_setenv asset-env-sync aws s3 cp s3://govuk-assets-production/cadfad06-b44e-45ee-8ffd-61da0c4e24c8 s3://govuk-assets-integration/

# List the asset in integration after it's been copied from production (note the updated timestamp)
$ aws s3 ls s3://govuk-assets-integration/cadfad06-b44e-45ee-8ffd-61da0c4e24c8
2017-11-14 15:44:05      91139 cadfad06-b44e-45ee-8ffd-61da0c4e24c8
```

**Comment by chrisroos** [comment]
I've used the `aws` cli to list the content of the govuk-assets-integration S3 bucket and, as far as I can tell, the sync was successful!

```
# List bucket content to file
$ aws s3 ls s3://govuk-assets-integration/ > integration-assets.txt

# Count of the number of objects in the bucket
$ wc -l integration-assets.txt 
   64989 integration-assets.txt

# Objects grouped by creation date - we can see that the vast majority were created today (as part of the overnight sync)
$ cat integration-assets.txt | cut -f1 -d" " | sort | uniq -c
   1 2017-11-06
 105 2017-11-07
   1 2017-11-14
64882 2017-11-15
```

I understand that using `aws s3 sync` doesn't copy files that already exist, which would explain why the single file I copied yesterday hasn't been touched.

**Comment by chrisroos** [comment]
In checking the number of assets stored on S3 I noticed that it differs from the number of records in the database and the number of files stored on NFS. I've created issue #301 to investigate this further.

**Comment by chrisroos** [comment]
I'm going to ask 2ndline for a list of the objects in the staging and production buckets so that we can check that everything has been copied as expected.

**Comment by chrisroos** [comment]
I think the following commands confirm that everything was copied to staging correctly:

```
$ wc -l staging-assets.txt 
   64989 staging-assets.txt

$ cat staging-assets.txt | cut -f1 -d" " | sort | uniq -c
   1 2017-11-14
64988 2017-11-15
```

**Comment by chrisroos** [comment]
There are more assets in the production bucket (65,017) than there are in staging and integration (64,989) but this difference (of 28) is explained by the assets that have been created in production since the overnight sync:

```
$ wc -l production-assets.txt 
   65017 production-assets.txt

$ grep 2017-11-15 production-assets.txt | wc -l
      28
```

**Comment by chrisroos** [comment]
I've copied the text files containing the S3 bucket listings to the Asset Manager folder in Google Drive.

**Comment by floehopper** [comment]
@chrisroos Thanks for all your work on this. Am I right in thinking we can close this issue now?

**Comment by chrisroos** [comment]
Yeah, I reckon so, @floehopper. Closing!
