### ISSUE TITLE
Regularly backup assets stored on S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#146]
We currently backup assets to S3 and possibly elsewhere. We'll need a similar backup solution in place once the canonical store of assets in on S3.

## Tasks

- [x] Run `rake govuk_assets:trigger_replication_for_non_replicated_assets` in production
- [x] Run `rake govuk_assets:check_all_assets_have_been_replicated` in production

**Comment by floehopper** [comment]
We can almost certainly use S3 bucket replication for this.

**Comment by floehopper** [comment]
Two nightly cron jobs are setup in production to backup assets to S3:

* [`/mnt/uploads/asset-manager` -> `s3://s3-eu-west-1.amazonaws.com/govuk-offsite-backups-production/asset-manager/`][1]
* [`/mnt/uploads/whitehall` -> `s3://s3-eu-west-1.amazonaws.com/govuk-offsite-backups-production/assets-whitehall/`][2]

Both these jobs are setup using [`backup::assets`][3], [`backup::offsite::job`][4] and the [vendored][6] [`puppet-duplicity` module][5].

**Note** both jobs use GPG to encrypt the backups.

[1]: https://github.com/alphagov/govuk-puppet/blob/1b99dbc24b0ac477fadb75ef8d1356dbfd58bf2e/hieradata/production.yaml#L21-L30
[2]: https://github.com/alphagov/govuk-puppet/blob/1b99dbc24b0ac477fadb75ef8d1356dbfd58bf2e/hieradata/production.yaml#L8-L20
[3]: https://github.com/alphagov/govuk-puppet/blob/1b99dbc24b0ac477fadb75ef8d1356dbfd58bf2e/modules/backup/manifests/assets.pp
[4]: https://github.com/alphagov/govuk-puppet/blob/1b99dbc24b0ac477fadb75ef8d1356dbfd58bf2e/modules/backup/manifests/offsite/job.pp
[5]: https://github.com/alphagov/puppet-duplicity/tree/388b8343188673dc966db8840ed5c4cf7ae00470/
[6]: https://github.com/alphagov/govuk-puppet/blob/1b99dbc24b0ac477fadb75ef8d1356dbfd58bf2e/Puppetfile#L44-L46

**Comment by floehopper** [comment]
There's an example of using Terraform to setup replication here: https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#using-replication-configuration

**Comment by floehopper** [comment]
I've opened alphagov/govuk-terraform-provisioning#140 & alphagov/govuk-terraform-provisioning#141 to address this.

**Comment by floehopper** [comment]
Once the S3 replication has been setup in production, we'll need to migrate the existing objects to the backup S3 bucket - replication only works for new operations carried out on the source bucket *after* it has been enabled, i.e. existing objects are not copied when you enable replication. I think we could use something like [`rclone`](https://rclone.org) to do this.

**Comment by chrisroos** [comment]
We've deployed the changes in https://github.com/alphagov/asset-manager/pull/288 which add the `rake govuk_assets:trigger_replication_for_non_replicated_assets` Rake task we're going to use to trigger replication for the existing assets in the S3 bucket. We're currently waiting for 2ndline to run this Rake task.

**Comment by chrisroos** [comment]
The `rake govuk_assets:trigger_replication_for_non_replicated_assets` ran successfully. The screenshot below shows the queue length increasing rapidly and then decreasing over the course of an hour as all the jobs were processed.

![screenshot 2017-11-03 15 09 38](https://user-images.githubusercontent.com/6556/32380917-4767f256-c0a9-11e7-9708-16b64e1aae39.png)

**Comment by chrisroos** [comment]
The `rake govuk_assets:check_all_assets_have_been_replicated` task is being/has been run on production. It was started at about 15:20 today and was 95% finished at 16:20. I'm hoping we'll get the output soon.

**Comment by chrisroos** [comment]
The output of the Rake task is:

```
Finished!
Assets with no S3 object: []
Assets with S3 object not replicated: []
Finished: SUCCESS
```

So I think this is all done!

**Comment by floehopper** [comment]
@chrisroos Thanks for all your work on this! 🎉 

I'm going to close this issue. I think there's some chance we *might* need to do some more work regarding backups in the light of the Slack conversation earlier in the week, but I think we can address that separately.
