### ISSUE TITLE
Upload all existing assets to S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#147]
We'll need to do this before we can start rolling out the nginx proxy to S3.

We have uploaded all existing assets in the integration environment to give us an idea of how long it should take in production (around 2 hours, details below). 

We now need to: 

- [x] Deploy `release_132` or later of `asset-manager` to production. 
- [x] Run `s3:upload_all_clean_assets[100]` via Jenkins on production
- [x] Monitor the progress of the task using `govuk_setenv asset-manager bundle exec rails runner 'p Delayed::Job.count'` run in `/var/apps/asset-manager` on a production machine.

**Comment by floehopper** [comment]
@chrislo & I have added a rake task to do this in #180. I suggest we keep this issue open until that has been run in production.

**Comment by chrislo** [comment]
We ran the rake task with 100% of all assets on integration. The rake task `s3:upload_all_clean_assets[100]` took 6 minutes to run (creating the background jobs). It reported `Total jobs enqueued: 58736`. 

To monitor the processing of these jobs we ran `puts "#{Time.now},#{Delayed::Job.count}"; sleep(1)` in a rails console within a `while true do` loop. 

The first job was processed at `11:51:53`, the final job at `14:03:56` - a total of 2 hours 12 minutes (or 7.4 jobs/s). 

The processing of jobs was continuous over the total time following a short ramp-up while the rake task ran:

![queue_length](https://user-images.githubusercontent.com/16707/30065706-ad48c422-924d-11e7-8f16-18178583e0bc.png)

**Comment by chrislo** [comment]
We also monitored some metrics in Graphite for `backend-1.backend.integration`.  There are other applications running on this machine. 

# Packets transmitted
<img width="623" alt="packets_transmitted" src="https://user-images.githubusercontent.com/16707/30066064-b3f5ba4a-924e-11e7-8498-86526c03516a.png">

# Load average
<img width="625" alt="load_average" src="https://user-images.githubusercontent.com/16707/30066075-bbf0beca-924e-11e7-8553-fb4dc2fa4abe.png">

# Memory
<img width="620" alt="memory" src="https://user-images.githubusercontent.com/16707/30066093-c9dbd4d4-924e-11e7-85b5-708631fe9aae.png">

**Comment by chrislo** [comment]
Based on the time it takes to process all of the jobs and the minimal impact it seems to have on the machines, I think we should be OK to run this task on production.

**Comment by chrislo** [comment]
With the help of @rubenarakelyan we're now running this task on production. `58853` jobs were enqueued.

**Comment by chrislo** [comment]
I asked @rubenarakelyan to monitor the queue length occasionally. 

```
10:50:46 - 52560 jobs
11:56:52 - 8968 jobs
```

It looks like production processed the queues at around 11 job/s.

**Comment by chrislo** [comment]
All of the assets are now on production, so this issue can be closed.
