### ISSUE TITLE
Ensure Last-Modified from nginx+s3proxy matches Last-Modified from nginx+Sendfile

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#148]
This is similar to issue #144.

We're imaging an incremental rollout of the nginx+s3proxy approach to serving assets. The same asset served from the two approaches currently have different values for the Last-Modified response header. I presume nginx+sendfile uses the modification date of the file on disk while nginx+s3proxy uses the modification date of the object on S3.

The same asset having different Last-Modified values (e.g. last-modified-1 and last-modified-2) may result in some additional load on the asset-manager servers because a conditional GET using last-modified-1 might end up with a 200 response and last-modified-2, instead of a 304 response for last-modified-1.

**Comment by floehopper** [comment]
I think @chrisroos effectively tested this in his testing of #164. For example, you can see that the `Last-Modified` header is the same whether Nginx serves the file from NFS or proxies it to S3 in the `curl` output in [this comment](https://github.com/alphagov/asset-manager/pull/164#issuecomment-325951294).

Closing.
