### ISSUE TITLE
Investigate the current requests/second against Asset Manager in production

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#150]
In particular we want a rough idea what the *maximum* requests/second is for a short period, e.g. 5 minutes and how often peaks of this kind occur. We want to compare these figures with the results of our performance tests to give us some confidence that the solution which proxies to S3 can handle similar loads.

**Comment by chrisroos** [comment]
I've made some notes about the investigation in our Google Doc (not public, unfortunately).

Assuming my investigation is valid, we currently see a maximum of about 4 requests/second to an individual Asset Manager nginx server.

**Comment by chrisroos** [comment]
I'm not sure there's much else to do for this so I'm closing it.

@floehopper / @chrislo - Please re-open it if you think there's more to do.
