### ISSUE TITLE
Check Range/If-Range behaviour

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#161]
As explained in [this document][1], if the server responds with and `Accept-Ranges` header with a value other than "none", the client can request the response in parts specified by a `Range` request header. The client can also make conditional `GET` requests using the `If-Range` request header.

We should see whether the current implementation supports `Range` requests and if so think about ensuring that the new implementation also works.

This is possibly related to #160.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by floehopper** [comment]
_Note: I've sorted the response headers in each of the responses in this comment in an effort to make it easier to compare responses._

Running against the code including the fix for HEAD requests in #172, I see the following behaviour when making a HEAD request for an asset:

### Nginx serving from NFS

```
$ curl -I http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt
HTTP/1.1 200 OK
Cache-Control: private
Connection: close
Content-Disposition: inline; filename="tmp.txt"
Content-Length: 0
Content-Transfer-Encoding: binary
Content-Type: text/plain
Date: Wed, 30 Aug 2017 15:38:58 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
X-Request-Id: d69d4bee-fc31-45d2-b0f5-2b71948a4644
X-Runtime: 0.008582
X-Xss-Protection: 1; mode=block
```

### Nginx proxying to S3

```
$ curl -I http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=0, private, must-revalidate
Connection: close
Content-Disposition: inline; filename="tmp.txt"
Content-Length: 29
Content-Type: text/plain
Date: Wed, 30 Aug 2017 15:39:59 GMT
ETag: "59a56480-1d"
Last-Modified: Tue, 29 Aug 2017 12:56:32 GMT
Server: nginx
```

In the latter case the response contains an extra `Accept-Ranges: bytes` header. This tells the client that the server can handle "Range" requests. Note that there are other differences which we might want to investigate. I see the following behaviour when sending "Range" requests:

### Nginx serving from NFS

```
$ curl -s -v -H "Range: bytes=0-5" http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Range: bytes=0-5
>
< HTTP/1.1 206 Partial Content
< Cache-Control: private
< Connection: close
< Content-Disposition: inline; filename="tmp.txt"
< Content-Length: 6
< Content-Range: bytes 0-5/29
< Content-Type: text/plain
< Date: Wed, 30 Aug 2017 15:46:24 GMT
< ETag: "59a56480-1d"
< Last-Modified: Tue, 29 Aug 2017 12:56:32 GMT
< Server: nginx
< Vary: Accept-Encoding
< X-Frame-Options: DENY
<
* Closing connection 0
Tue 29
```

### Nginx proxying to S3

```
$ curl -s -v -H "Range: bytes=0-5" http://asnager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1 HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Range: bytes=0-5
>
< HTTP/1.1 206 Partial Content
< Accept-Ranges: bytes
< Cache-Control: max-age=0, private, must-revalidate
< Connection: close
< Content-Disposition: inline; filename="tmp.txt"
< Content-Length: 6
< Content-Range: bytes 0-5/29
< Content-Type: text/plain
< Date: Wed, 30 Aug 2017 15:47:04 GMT
< ETag: "59a56480-1d"
< Last-Modified: Tue, 29 Aug 2017 12:56:32 GMT
< Server: nginx<
* Closing connection 0
Tue 29
```

Broadly speaking this seems to work in both cases, even though the "Nginx serving from NFS" HEAD response doesn't advertise its ability to serve such requests.

There are other differences in the response headers which we might want to investigate.

**Comment by chrisroos** [comment]
> There are other differences in the response headers which we might want to investigate.

@floehopper: It might be worth running asset-manager in the production environment to see whether any of these differences go away. It should at least make the `Cache-Control` headers the same for assets served from NFS and from S3.

**Comment by floehopper** [comment]
I've also tried making "Range" requests with out-of-range values:

### Nginx serving from NFS

```
$ curl -s -v -H "Range: bytes=50-100" http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Range: bytes=50-100
>
< HTTP/1.1 416 Requested Range Not Satisfiable
< Cache-Control: private
< Connection: close
< Content-Disposition: inline; filename="tmp.txt"
< Content-Length: 206
< Content-Range: bytes */29
< Content-Type: text/html
< Date: Wed, 30 Aug 2017 16:09:48 GMT
< Server: nginx
< Vary: Accept-Encoding
< X-Frame-Options: DENY
<
<html>
<head><title>416 Requested Range Not Satisfiable</title></head>
<body bgcolor="white">
<center><h1>416 Requested Range Not Satisfiable</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Closing connection 0
```

### Nginx proxying to S3

```
$ curl -s -v -H "Range: bytes=50-100" http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1 HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Range: bytes=50-100
>
< HTTP/1.1 416 Requested Range Not Satisfiable
< Cache-Control: max-age=0, private, must-revalidate
< Connection: close
< Content-Disposition: inline; filename="tmp.txt"
< Content-Type: application/xml
< Date: Wed, 30 Aug 2017 16:11:30 GMT
< Server: nginx
< Transfer-Encoding: chunked
<
<?xml version="1.0" encoding="UTF-8"?>
* Closing connection 0
<Error><Code>InvalidRange</Code><Message>The requested range is not satisfiable</Message><RangeRequested>bytes=50-100</RangeRequested><ActualObjectSize>29</ActualObjectSize><RequestId>C51593B470CE06B9</RequestId><HostId>Mnna4AfEI969GLii53yzxQMARSR9qgPme7Seq5E/q+mapfNU2LuCtVEXr3AJL1s40gFopItPN3Y=</HostId></Error>
```

Again broadly speaking this all looks OK, although there are some differences which we might want to investigate, notably the response body is HTML when Nginx serves from NFS, but XML when Nginx proxies to S3. We might want to consider the latter in #139.

**Comment by floehopper** [comment]
@chrisroos, @chrislo: I'm afraid I've run out of time on this. Perhaps one of you can take over where I've left of...?

**Comment by floehopper** [comment]
@chrisroos:

> It might be worth running asset-manager in the production environment to see whether any of these differences go away. It should at least make the `Cache-Control` headers the same for assets served from NFS and from S3.

Oh, yeah. I keep forgetting about that. It's really annoying!

**Comment by chrisroos** [comment]
I'm going to take a look at this now.

**Comment by chrisroos** [comment]
I made a number of requests to the various components in our asset-manager stack to determine when the Accept-Ranges header was being set:

| Request target  | Request method | Accept-Ranges header |
| --------------- | -------------- | -------------------- |
| Rails app + NFS | HEAD           | No                   |
| Rails app + NFS | GET            | No                   |
| Rails app + S3  | HEAD           | No                   |
| Rails app + S3  | GET            | No                   |
| Signed S3 URL   | HEAD           | Yes                  |
| Signed S3 URL   | GET            | Yes                  |
| nginx + NFS     | HEAD           | No                   |
| nginx + NFS     | GET            | Yes                  |
| nginx + S3      | HEAD           | Yes                  |
| nginx + S3      | GET            | Yes                  |

I _think_ this helps explain the behaviour we see when making requests to nginx:

* Presumably we see the Accept-Ranges header added for both HEAD and GET requests to nginx+S3 because the header is set on S3 itself and [Accept-Ranges is one of the headers that isn't modified when returned by the proxy][nginx-xsendfile].

* Presumably we don't see the Accept-Ranges header when making a HEAD request to nginx+NFS because the Rails app (using `sendfile`) doesn't set this header.

* Presumably we see the Accept-Ranges header when making a GET request to nginx+NFS because nginx knows that it's serving the file from disk and that it can read/serve partial content of that file.

[nginx-xsendfile]: https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/

**Comment by chrisroos** [comment]
I think the ["Smart and Efficient Byte-Range Caching with NGINX & NGINX Plus" article][nginx-byte-ranges] explains what happens when nginx receives a byte-range request for content hosted on S3:

> When NGINX receives a byte‑range request for uncached content, it requests the entire file (not a byte range) from the origin server and begins streaming the response to temporary storage.

We haven't configured any caching for assets served from S3 so I think the paragraph above applies to all byte-range requests we receive to nginx + S3.

[nginx-byte-ranges]: https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/

**Comment by chrisroos** [comment]
I started looking at the number of HEAD requests and 206 responses we see at the CDN. Based on the [data we've got from the logs covering 18 Aug 2017][asset-manager-google-doc] (not public unfortunately):

* 339 HEAD requests out of 446774 total requests = 0.076%
* 8035 206 responses out of 446774 total responses = 1.8%

I then wondered how Fastly handles byte-range requests and came across this answer in one of their [support threads][fastly-support-thread]:

> The default behavior for Fastly is to strip the range header from the request to origin. Fastly fetches the full object. If there is a partial content request, we also strip the content-range header in vcl_fetch based on the assumption we have the full object in cache and can serve based on content-length.

I'd like to find a more definitive source of this information but have been unable to.

[asset-manager-google-doc]: https://docs.google.com/document/d/1Ws6EdQGShKrfcbN5Ke0wVGU_dvCjY17SsrekoWvDzQo/edit
[fastly-support-thread]: https://community.fastly.com/t/http-range-header-and-206-partial-content-responses/627/2

**Comment by chrisroos** [comment]
In summary:

* There's a small difference in the HTTP response from the asset-manager nginx server when using `HEAD` to request an asset from the filesystem vs requesting it from S3 (`Accept-Bytes` is absent in the former and present in the latter).

* The asset-manager nginx server honours byte-range requests for assets stored on S3 but it does this by downloading the whole file from S3 and waiting until it has enough to satisfy the byte-range request.

* In production I believe the CDN will handle any byte-range requests and that we won't see any of them coming through to the asset-manager nginx server.

All of which makes me think that we're all good as we are and that we don't need to do anything else!

Does this all make sense to you, @floehopper and @chrislo?

**Comment by floehopper** [comment]
@chrisroos: That all makes sense to me, especially given the last point in your summary about the CDN handling all the byte-range requests in production. Thus I think it's OK to close this issue without doing any further work.

**Comment by chrisroos** [comment]
Thanks @floehopper! I'm going to close this issue given that we're happy with the behaviour as it stands.
