### ISSUE TITLE
Check that clients can request compressed content when proxying to S3 via Nginx

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#165]
If the current default mechanism responds with compressed files when a client says it accepts them (e.g. using a `Accept-Encoding: gzip` request header), then we should ensure the new mechanism also supports this.

**Comment by chrisroos** [comment]
There's probably some useful info under "Serving compressed assets" in our [Google doc](https://docs.google.com/document/d/1Ws6EdQGShKrfcbN5Ke0wVGU_dvCjY17SsrekoWvDzQo/edit#heading=h.1nfv01twksz) (not public, unfortunately).

**Comment by floehopper** [comment]
The following shows a comparison of what happens if we request a plain text asset specifying an `Accept-Encoding: gzip` request header either (a) when Nginx serves the file from NFS; or (b) when Nginx proxies the request to S3:

### Nginx serves the file from NFS

```
$ curl -s -v -H "Accept-Encoding: gzip" http://asset-manager.dev.gov.uk/media/59a5647f759b7445a47/tmp.txt >/dev/null
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 30 Aug 2017 14:01:05 GMT
< Content-Type: text/plain
< Last-Modified: Tue, 29 Aug 2017 12:56:32 GMT
< Transfer-Encoding: chunked
< Connection: close
< Vary: Accept-Encoding
< Content-Disposition: inline; filename="tmp.txt"
< Cache-Control: private
< X-Frame-Options: DENY
< Content-Encoding: gzip
<
{ [60 bytes data]
* Closing connection 0
```

### Nginx proxies the request to S3

```
$ curl -s -v -H "Accept-Encoding: gzip" http://asset-manager.dev.gov.uk/media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1 >/dev/null
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /media/59a5647f759b744518bdaa47/tmp.txt?proxy_to_s3_via_nginx=1 HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 30 Aug 2017 14:01:21 GMT
< Content-Length: 29
< Connection: close
< Content-Disposition: inline; filename="tmp.txt"
< Cache-Control: max-age=0, private, must-revalidate
< Last-Modified: Tue, 29 Aug 2017 12:56:32 GMT
< ETag: "59a56480-1d"
< Accept-Ranges: bytes
< Content-Type: text/plain
<
{ [29 bytes data]
* Closing connection 0
```

The above demonstrates that the server cannot currently serve compressed assets when configured to proxy requests to S3.

However, given that [the vast majority of mainstream assets are PDFs][1], we don't think it is a significant issue and are happy to proceed.

[I've captured the idea of making it possible to serve compressed assets when proxying to S3 in a new issue][2].

@chrisroos, @chrislo: Are you happy for me to close this issue?

[1]: https://github.com/alphagov/asset-manager/blob/283ab9d56b16609c26aecc791b63bca0cfa90fc2/docs/existing_assets.md#file-extensions
[2]: https://github.com/alphagov/asset-manager/issues/168

**Comment by chrisroos** [comment]
I'm happy for this to be closed, @floehopper.

**Comment by floehopper** [comment]
Cool. Closing.
