### ISSUE TITLE
Run `migrate:add_uuid_to_assets` on all environments

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#174]
This data migration task was added in https://github.com/alphagov/asset-manager/pull/173. It will need running on all environments when deployed.

**Comment by chrisroos** [comment]
I just [ran this Rake task in integration using the Run Rake task job in Jenkins][jenkins-2861]. It took 6 min 10 sec to complete.

I think we should ask in Slack tomorrow whether this is a reasonable time for a task to be running for.

[jenkins-2861]: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/2861/

**Comment by chrisroos** [comment]
I'm going to see whether we can get this run on staging and production now that we've just deployed the most recent code changes.

**Comment by chrisroos** [comment]
This has now been run in staging and production. We used the following command to ensure that the Rake task had completed successfully: `$ govuk_setenv asset-manager bundle exec rails r "puts Asset.where(uuid: nil).count"`. It returned `0` in both staging and production.

**Comment by chrisroos** [comment]
I don't think there's anything more to do for this issue so I'm closing it. cc/ @chrislo.
