### ISSUE TITLE
Use Sidekiq instead of Delayed Job

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#179]
This was suggested when we asked whether there were any supported ways of viewing the status of Delayed Job queues. The majority of apps use Sidekiq and there's already [support for monitoring these queues](https://docs.publishing.service.gov.uk/manual/monitor-sidekiq-workers.html).

TODO: 
- [x] Configure sidekiq in asset manager
- [x] Setup redis configuration in puppet
- [x] Setup worker process in puppet
- [x] Make sure worker is restarted on deployment in govuk-app-deployment
- [x] Configure [monitoring of sidekiq](https://docs.publishing.service.gov.uk/manual/setting-up-new-sidekiq-monitoring-app.html)
- [x] Migrate virus worker job to sidekiq
- [x] Migrate s3 uploaded job to sidekiq
- [ ] Remove delayed job

**Comment by tijmenb** [comment]
FYI: https://github.com/alphagov/govuk_sidekiq contains configuration and explains how to set up Sidekiq on GOV.UK.

**Comment by chrislo** [comment]
The following branches are relevant: 

- [asset-manager/migrate-to-sidekiq-from-delayed-job](https://github.com/alphagov/asset-manager/tree/migrate-to-sidekiq-from-delayed-job)
- [govuk-puppet/configure-sidekiq-for-asset-manager](https://github.com/alphagov/govuk-puppet/tree/configure-sidekiq-for-asset-manager)
- [govuk-app-deployment/restart-asset-manager-sidekiq-on-deployment](https://github.com/alphagov/govuk-app-deployment/tree/restart-asset-manager-sidekiq-on-deployment)

**Comment by chrislo** [comment]
I've [opened a PR](https://github.com/alphagov/govuk-puppet/pull/6483) for the `govuk-puppet` changes, and [one for](https://github.com/alphagov/govuk-app-deployment/pull/178) the `govuk-app-deployment` changes.

**Comment by chrislo** [comment]
With the above two PRs merged monitoring of the queues now seems to work on integration. You can see the sidekiq dashboard by forwarding a port on integration (`ssh backend-1.backend.integration -CNL 9000:127.0.0.1:80`) and then visiting http://localhost:9000/asset-manager. 

I asked in Slack and @cbaines mentioned that the queue length should appear on [the grafana dashboard](https://grafana.integration.publishing.service.gov.uk/dashboard/file/sidekiq.json) when the first jobs appear on the sidekiq queue (there are currently no workers configured for Asset Manager - that's the next step).

**Comment by floehopper** [comment]
@chrislo: Good work! 😄

**Comment by chrislo** [comment]
I opened #221 and #227 to migrate the two delayed job workers to sidekiq.

**Comment by chrislo** [comment]
Sidekiq queue monitoring is available now through the grafana Sidekiq dashboard.

**Comment by chrislo** [comment]
Delayed job has been removed in #232. 

This issue is now closed, but on deployment we could check that `Delayed::Job.count` is `0` just to make sure no work is on the delayed job queue before deploying.
