### ISSUE TITLE
Use Sentry instead of Errbit

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#184]
Instructions for upgrading are available at https://docs.publishing.service.gov.uk/manual/upgrade-to-sentry.html.

**Comment by floehopper** [comment]
This should probably wait for [Use Sidekiq instead of Delayed Job](https://github.com/alphagov/asset-manager/issues/179), because it requires Sidekiq to be setup.

**Comment by cbaines** [comment]
> This should probably wait for Use Sidekiq instead of Delayed Job, because it requires Sidekiq to be setup.

I don't think it does. If you are looking at the bit about `govuk_sidekiq`, I think that is only relevant if you are using `govuk_sidekiq` already.

**Comment by floehopper** [comment]
@cbaines: Ah, OK. Thanks for pointing that out! 😄
