### ISSUE TITLE
Make Asset#uuid read-only

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#196]
Possibly using [`Mongoid::Attributes::Readonly::ClassMethods#attr_readonly`][1].

[1]: http://www.rubydoc.info/github/mongoid/mongoid/Mongoid/Attributes/Readonly/ClassMethods#attr_readonly-instance_method

**Comment by chrisroos** [comment]
I've opened PR #209 to make `Asset#uuid` read-only.

**Comment by chrisroos** [comment]
PR #209 has been merged so this issue can be closed.
