### ISSUE TITLE
Serve Whitehall images from Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#200]

**Comment by floehopper** [comment]
This supersedes #185 & #186.

**Comment by floehopper** [comment]
We've extracted #201 as a separate issue.

**Comment by floehopper** [comment]
We've extracted #202 as a separate issue.

**Comment by floehopper** [comment]
I've extracted #203 as a separate issue.

**Comment by floehopper** [comment]
I've just pushed up a bunch of changes related to the first few checklist items in [this branch](https://github.com/alphagov/asset-manager/compare/serve-public-whitehall-assets-from-asset-manager). I plan to check through them in the morning before hopefully opening a PR.

**Comment by floehopper** [comment]
I've extracted #211 as a separate issue.

**Comment by floehopper** [comment]
@chrisroos has extracted #212 as a separate issue.

**Comment by floehopper** [comment]
I've extracted #213 as a separate issue.

**Comment by chrisroos** [comment]
I've created issue #214 about updating the nginx config to serve Whitehall images from Asset Manager.

**Comment by chrisroos** [comment]
This issue previously contained a number of checklist items in the description detailing what we'd need to do to get this working. We've now extracted each of these items to new issues in the "Store and serve Whitehall images in/from Asset Manager" so I'm closing this issue.
