### ISSUE TITLE
Enable asset pre-compilation for Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#201]
Enable asset pre-compilation for Asset Manager in the govuk-app-deployment repo now that we've merged #199.

We think we'll want something like [these lines](https://github.com/alphagov/govuk-app-deployment/blob/7b75260028deb05ad85ce2bf26b2338b7b413e4a/static/config/deploy.rb#L7-L9).

**Comment by chrisroos** [comment]
@floehopper made this change in https://github.com/alphagov/govuk-app-deployment/pull/183.

**Comment by floehopper** [comment]
@bevanloon has just confirmed that the `assets:precompile` rake task ran as part of the production deployment, so I'm happy to close this issue.

```
* executing `deploy:assets:precompile'
  * executing "cd /data/apps/asset-manager/releases/20170920141708 && govuk_setenv asset-manager bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile"
```
