### ISSUE TITLE
Add Nginx configuration for Asset Manager Rails asset pipeline assets

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#202]
Now that we've merged #199, we should add asset-manager to [this list](https://github.com/alphagov/govuk-puppet/blob/994d5424c7e4e28e903039f9f603e8d345b4f01d/hieradata/common.yaml#L1545-L1566).

**Comment by chrisroos** [comment]
@floehopper has made this change in https://github.com/alphagov/govuk-puppet/pull/6502.

**Comment by floehopper** [comment]
This change is now live on staging and I can see the [placeholder image](https://assets-origin.staging.publishing.service.gov.uk/asset-manager/thumbnail-placeholder.png).

**Comment by floehopper** [comment]
This change is now live on production and I can see the [placeholder image](https://assets-origin.publishing.service.gov.uk/asset-manager/thumbnail-placeholder.png).
