### ISSUE TITLE
Refactor PublicUploadsController

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#213]
The PublicUploadsController is used for three things:

1. Redirect all requests using relative URLs for non-attachment assets (e.g. '/government/uploads/system/uploads/person/image/person.png') to the asset host (and therefore Asset Manager)
2. Serve a small number of fixed HMRC assets in /uploaded/hmrc
3. Act as the super class for AttachmentController

I think there's likely to be relative URLs to assets burnt into published documents, so its unlikely we can remove the controller altogether as it will still need to do 1.

Whether or not we can stop doing 2. depends on #217. 

If we refactor the controller to make the three responsibilities clear I think it will make it easier to remove pieces of it later.

---------
# Previous issue description 

Once we're happy that it's no longer being used, i.e. all publicly accessible Whitehall assets are now being served by Asset Manager.

It might also be worth considering removing `app/assets/images/thumbnail-placeholder.png`, although it looks as if it _might_ be used in [`PlaceholderController#placeholder_image`](https://github.com/alphagov/whitehall/blob/4f265d5f321fa2deb18b3d8a1089cf3a439b2864/app/controllers/placeholder_controller.rb#L7-L9).

**Comment by chrislo** [comment]
This issue depends a bit on what we decide to do with the HMRC assets in #217. If we leave them on NFS we can rename this controller to make it clear that it only serves HMRC assets and simplify it. If we can migrate those assets we can delete this controller altogether.

**Comment by chrislo** [comment]
I'm going to refactor the public uploads controller to remove some of the redundant code and split out the code that serves HMRC assets into a separate controller. I think that'll make it easier to do something with this issue at a later date.

**Comment by chrislo** [comment]
This refactor (https://github.com/alphagov/whitehall/pull/3763) has now been deployed to production.
