### ISSUE TITLE
Configure Nginx to serve Whitehall non-attachment assets from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#214]
Once we've uploaded all existing Whitehall non-attachment assets to Asset Manager, and all other assets served by the PublicUploadsController, and we're uploading all new image assets to Asset Manager, we'll be in a position to update the nginx configuration to point /government/uploads to Asset Manager.

We'll need to make sure that `/government/uploads/system/uploads/consultation_response_form/` and `/government/uploads/system/uploads/attachment_data/file` continue to be served by Whitehall as these aren't handled by the PublicUploadsController (see https://github.com/alphagov/whitehall/blob/master/config/routes.rb#L419-L421 for more info).

Our spike branches in issue #185 should help with this work.

* [ ] Before we implement this in production, we should double-check the response headers for Whitehall assets served from Asset Manager match those for the same assets served by Whitehall (see #220 for more details).
* [ ] Depending on whether we've addressed #216 & #217 before we do this, we might need to only send a subset of URL paths under `/government/uploads` to Asset Manager.

**Comment by floehopper** [comment]
Depending on whether we've addressed #216 & #217 before we do this, we might need to only send a subset of URL paths under `/government/uploads` to Asset Manager.

**Comment by floehopper** [comment]
Although we could make the changes to `govuk-puppet`, etc, beforehand, we can't deploy the changes until #214, #215, #229, #244 & #245 have been implemented and deployed. Marking as blocked.

**Comment by chrislo** [comment]
This issue has been made redundant by the nginx changes we have been making as we migrate each type of asset. 

However, when we have finally moved all assets to Asset Manager we may be able to make some simplifications to the nginx config to avoid having so many explicit paths.
