### ISSUE TITLE
Migrate all Whitehall ImageUploader-backed assets to Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#215]
From #341 these are the remaining assets that need to be migrated as part of this task.

| Model                                  | Uploader                         | path                                                       | count   | total size |
|----------------------------------------|----------------------------------|------------------------------------------------------------|---------|------------|
| ClassificationFeaturingImageData\#file | ImageUploader                    | `system/uploads/classification_featuring_image_data/file`  | 15498   | 2.0 GiB    |
| DefaultNewsOrganisationImageData\#file | ImageUploader                    | `system/uploads/default_news_organisation_image_data/file` | 1862    | 264.7 MiB  |
| Feature\#image                         | ImageUploader                    | `system/uploads/feature/image`                             | 473781  | 55.1 GiB   |
| ImageData\#file                        | ImageUploader                    | `system/uploads/image_data/file`                           | 494970  | 57.5 GiB   |
| Person\#image                          | ImageUploader                    | `system/uploads/person/image`                              | 23927   | 2.0 GiB    |
| PromotionalFeatureItem\#image          | ImageUploader                    | `system/uploads/promotional_feature_item/image`            | 371     | 12.8 MiB   |
| TakePartPage\#image                    | ImageUploader                    | `system/uploads/take_part_page/image`                      | 147     | 18.2 MiB   |

Note that `Classification#logo` also [mounts the ImageUploader](https://github.com/alphagov/whitehall/blob/e42d4bc787828a3da77de89891a8c44e04c6cfd5/app/models/classification.rb#L61) but there are no associated files stored on NFS.

- [x] Run `asset_manager:migrate_assets[system/uploads/promotional_feature_item/image]` on production
- [x] Run `asset_manager:migrate_assets[system/uploads/take_part_page/image]` on production
- [x] Run `asset_manager:migrate_assets[system/uploads/default_news_organisation_image_data/file]` on production
- [x] Run `asset_manager:migrate_assets[system/uploads/classification_featuring_image_data/file]` on production
- [x] Run `asset_manager:migrate_assets[system/uploads/person/image]` on production
- [x] Run `asset_manager:migrate_assets[system/uploads/feature/image]` on production

**Comment by floehopper** [comment]
This work feels quite dependent on #212, so it's probably worth holding off until we've made some progress on that.

**Comment by floehopper** [comment]
I've added a note to the description to explain that we should set `legacy_etag` and `legacy_last_modified` when creating these assets via the Asset Manager API.

**Comment by floehopper** [comment]
This has been unblocked as per [this comment](https://github.com/alphagov/asset-manager/pull/257#issuecomment-335834927).

**Comment by floehopper** [comment]
We discussed this just now and agreed that it's somewhat dependent on how we approach #244 & #245 - more specifically whether we end up storing an identifier returned from Asset Manager when an asset is created. Marking as blocked.

**Comment by chrislo** [comment]
#244 and #245 have been closed and #325 has been merged. When it has been deployed and we are satisfied that new assets are being uploaded to Asset Manager I think we can start to migrate the existing assets.

**Comment by chrislo** [comment]
It might be worth comparing the assets that need to be migrated with the directory structure that currently exists

```
@integration-whitehall-backend-1:/data/uploads/whitehall/clean/system/uploads$ tree -d -L 2
.
├── attachment
│   └── file
├── attachment_data
│   └── file
├── classification_featuring_image_data
│   └── file
├── consultation_response_form
│   └── file
├── consultation_response_form_data
│   └── file
├── default_news_organisation_image_data
│   └── file
├── edition_organisation_image_data
│   └── file
├── edition_world_location_image_data
│   └── file
├── feature
│   ├── file
│   └── image
├── image_data
│   └── file
├── news_article
│   ├── featuring_image
│   └── image
├── organisation
│   └── logo
├── person
│   └── image
├── promotional_feature_item
│   └── image
├── take_part_page
│   └── image
└── topical_event
    └── logo
```

Not for example that `feature/file` does not have a current Uploader mounted on it.

**Comment by chrislo** [comment]
We want to migrate these assets in stages for two reasons: 
1. So that we can monitor the performance of asset manager to make sure it can cope with serving additional requests for these assets
2. Between migrating the assets and deleting them we double the disk space used in NFS (as they're stored under the whitehall NFS directory and the Asset Manager NFS directory). We don't want to block this task on [milestone/5](https://github.com/alphagov/asset-manager/milestone/5).

I've sketched out the sequence of tasks in a checklist above, starting with the smallest batch of assets and moving to the largest. We can add some details to the checklist as we go.

**Comment by chrislo** [comment]
The `asset_manager:migrate_assets[system/uploads/promotional_feature_item/image]` task was run in production by @leenagupte at 8:53. 371 files were added to the `asset_migration` queue. The queue was empty (according to Grafana) by 8:54.

**Comment by chrislo** [comment]
The following tasks were run on production by @maxgds:

- `asset_manager:migrate_assets[system/uploads/take_part_page/image]`: 147 files, completed in < 1 minute 
- asset_manager:migrate_assets[system/uploads/default_news_organisation_image_data/file]: 1862 files, completed in ~3 minutes
- asset_manager:migrate_assets[system/uploads/classification_featuring_image_data/file]: 15512 files, completed in ~30 minutes.

There was [one timeout exception](https://sentry.io/govuk/app-whitehall/issues/401840961/) thrown by the worker but it succeeded on retry. 

This is a graph of the whitehall `asset_migration` queue length for the three tasks.

<img width="1322" alt="screen shot 2017-12-18 at 10 48 47" src="https://user-images.githubusercontent.com/16707/34114819-c44fe89a-e3e1-11e7-9ed7-d4ad1e9ddfb5.png">

**Comment by chrislo** [comment]
@chrisroos @floehopper - you could continue working through this issue if you get chance. There's some more rake tasks to ask second line to run. You just need to check that the number of enqueued jobs as reported by the rake task is the same (or larger) than the number in the table above, and then monitor the queues in Grafana. 

I only have a placeholder checklist for the nginx changes because I'm not sure what that will look like in the end (c.f. #214). 

There's a rake task `asset_manager:remove_organisation_logos` that can be modified to do the actual deletion from NFS. You may want to change that task so that it outputs a count rather than a full list of deleted files. Or you could ask someone to just remove the files "by hand".

**Comment by chrislo** [comment]
We shouldn't migrate any more assets until we are sure that [hidden files are also being migrated](https://github.com/alphagov/asset-manager/issues/368).

**Comment by chrislo** [comment]
The changes to the migration rake task to ensure that files that start with a `.` are migrated have been deployed. Removing the `blocked` label.

**Comment by chrislo** [comment]
I asked @Davidslv to run the `asset_manager:migrate_assets[system/uploads/person/image]` task at [11:38:33](https://deploy.publishing.service.gov.uk/job/run-rake-task/2308/console) today. `24039` were enqueued.

**Comment by chrislo** [comment]
The `asset_manager:migrate_assets[system/uploads/person/image]` task has completed. There was [one GdsApi::TimedOutException](https://sentry.io/govuk/app-whitehall/issues/401840961/) which hasn't occurred again so I assume it succeeded on retry. 

I monitored the [whitehall sidekiq queue](https://grafana.publishing.service.gov.uk/dashboard/db/sidekiq-older-versions-of-govuk_sidekiq?refresh=1m&orgId=1&var-Application=whitehall&var-Queues=All&from=now-3h&to=now)

<img width="1145" alt="screen shot 2018-01-05 at 08 09 18" src="https://user-images.githubusercontent.com/16707/34610655-1267c55e-f1f0-11e7-9779-45a5226d323c.png">

And the [asset manager sidekiq queue](https://grafana.publishing.service.gov.uk/dashboard/file/deployment_asset-manager.json?refresh=5s&orgId=1&panelId=5&fullscreen&from=now-3h&to=now)

<img width="1148" alt="screen shot 2018-01-05 at 08 09 26" src="https://user-images.githubusercontent.com/16707/34610668-23a56d58-f1f0-11e7-99d5-2c649807c9b8.png">

during the migration. It took around 1hr to migrate the 24039 assets.

**Comment by chrislo** [comment]
Since we implemented https://github.com/alphagov/asset-manager/issues/323 to delete assets from NFS as soon as they have been uploaded to S3 the change in NFS disk usage during the migration of the 2GB of person images was only 30Mb (I attribute this to other uploads to whitehall happening during that time). 

<img width="1145" alt="screen shot 2018-01-05 at 08 14 36" src="https://user-images.githubusercontent.com/16707/34610872-fe6f33e2-f1f0-11e7-8857-feb4a929b46e.png">

/cc @floehopper

**Comment by chrislo** [comment]
We ran `asset_manager:migrate_assets[system/uploads/feature/image]` against production at [13:35:34](https://deploy.publishing.service.gov.uk/job/run-rake-task/2310/console). 477113 files were queued for migration. 

The rake task itself took around 30 minutes to run and it doesn't currently give any indication of progress. It might be worth adding something if we ever need to run it for much more than this number of files.

**Comment by chrislo** [comment]
The `asset_migration` queue was empty by around 08:15 on 2018-01-07. It took [around 42 hours](https://www.timeanddate.com/date/durationresult.html?d1=5&m1=1&y1=2018&d2=7&m2=1&y2=2018&h1=13&i1=35&s1=00&h2=08&i2=15&s2=00) to process the queue. 

There are 42 jobs currently in the retry set which are due to some files having non-ascii file names. This is being investigated in #384.

**Comment by chrislo** [comment]
While the task run I noticed that the number of jobs per second processed by asset manager as reported on [the new grafana dashboard](https://grafana.publishing.service.gov.uk/dashboard/file/deployment_asset-manager.json?refresh=30s&orgId=1&panelId=5&fullscreen&from=now-4d&to=now) steadily decreased 

<img width="1354" alt="screen shot 2018-01-07 at 07 05 13" src="https://user-images.githubusercontent.com/16707/34668513-bedc8ca0-f43b-11e7-8f32-340420c2e623.png">

**Comment by chrislo** [comment]
We started `asset_manager:migrate_assets[system/uploads/image_data/file]` running today at 13:30.

**Comment by chrislo** [comment]
The rake task completed at `13:45:11`. 498883 files were queued for migration.

**Comment by chrislo** [comment]
There was a deployment to production of whitehall at around 15:40 today. At that point we noticed a spike in [GdsApi::HTTPUnprocessableEntity](https://sentry.io/govuk/app-whitehall/issues/343661139/) exceptions and inspecting the Grafana graph it appeared that no migration worker jobs were being processed

<img width="1358" alt="screen shot 2018-01-08 at 12 35 05" src="https://user-images.githubusercontent.com/16707/34683724-e72b6372-f470-11e7-9f25-a0b72e405818.png">

At 17:31 @suzannehamilton cleared the jobs on the `asset_migration` queue by running

```
q = Sidekiq::Queue.new("asset_migration")
q.clear
```

on a production whitehall console. 

We could see that jobs were being queued and enqueued on the `publishing_api` queue at this time so we don't think it was a case that all of the workers had failed to start after the deployment. 

It should be safe to run the `asset_manager:migrate_assets[system/uploads/image_data/file]` task again once we understand what is happening. This will create assets with the same `legacy_url_path` as some of the assets that had been migrated at that point, but the existing ones will be marked as deleted in Asset Manager. If this isn't desirable, I think we could manually remove the assets with `system/uploads/image_data/file` in the legacy path from the asset manager database before running the task again.

**Comment by chrisroos** [comment]
Our theory is that these jobs started failing after the deployment because [`AssetFile#legacy_url_path`](https://github.com/alphagov/whitehall/blob/5cc886066a869243a16cc8b87ef67b9021d4d57e/lib/migrate_assets_to_asset_manager.rb#L68) no longer returned a valid path. This is because the absolute path stored in the enqueued job no longer matched the value of `Whitehall.clean_uploads_root`. We _could_ wait to run this job over the weekend to avoid the problem of there being a deployment but it's probably better to make the jobs more resilient to deployments.

We should also clear the retry queue of these specific jobs. We should be aware of the 42 jobs in that queue as described in https://github.com/alphagov/asset-manager/issues/215#issuecomment-355939968. It's probably OK to remove these from the retry queue too given that we know the paths and so can re-upload them once we have a fix in place for that particular problem.

I think it might also make sense to rename the [`Worker`](https://github.com/alphagov/whitehall/blob/5cc886066a869243a16cc8b87ef67b9021d4d57e/lib/migrate_assets_to_asset_manager.rb#L18) so that it's easier to understand what it is when it appears in various dashboards (e.g. the [whitehall deployment dashboard](https://grafana.publishing.service.gov.uk/dashboard/file/deployment_whitehall.json?refresh=5s&orgId=1)).

**Comment by chrisroos** [comment]
I've extracted the remaining items in the checklist to separate issues as I think it'll make it slightly easier to manage:

* Serve Whitehall's promotional feature images from Asset Manager #398 
* Serve Whitehall's take part page images from Asset Manager #399
* Serve Whitehall's default news organisation images from Asset Manager #400
* Serve Whitehall's classification featuring images from Asset Manager #401
* Serve Whitehall's people images from Asset Manager #402
* Serve Whitehall's feature images from Asset Manager #403
* Serve Whitehall's images from Asset Manager #404
* Remove Whitehall's non-attachment assets from NFS #405

I'm going to remove the outstanding items from the checklist in the description too.

**Comment by chrisroos** [comment]
I'm closing this now that the remaining work has been captured in other issues.
