### ISSUE TITLE
Change Whitehall so that it can replace non-attachment assets in Asset Manager

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#245]
Arises from: #212 

Add the ability to replace images in Asset Manager when they're replaced on the local file system. 

We've investigated replacing assets in asset manager in #229. There may be some changes needed in asset manager to support this - but we'll need to explore what Whitehall actually needs to do before changing asset manager.

**Comment by floehopper** [comment]
When we work on this, we should consider what should happen to any values stored in `Whitehall#legacy_etag` and `#legacy_last_modified` in Asset Manager when an asset is updated. See [this comment](https://github.com/alphagov/asset-manager/pull/257#issuecomment-335421556) for more details.

**Comment by floehopper** [comment]
We discussed this just now and agreed that this work is somewhat dependent on #244, so I'm going to mark it as blocked.

**Comment by chrisroos** [comment]
I've removed the blocked label now that #244 has been closed.

**Comment by chrislo** [comment]
I think this issue can be addressed by making a `POST` to `/whitehall_assets` with an existing `legacy_url_path` replace the existing asset. #336 makes that change.

**Comment by chrislo** [comment]
https://github.com/alphagov/whitehall/pull/3602 uses the modified `/whitehall_assets` `POST` endpoint to soft-delete existing assets when they are replaced by ones with the same filename (in the case of Person images in Whitehall for example). Replacing an image with one with a different filename is also addressed in https://github.com/alphagov/whitehall/pull/3602. 

I think this issue can be closed.
