### ISSUE TITLE
Switch to using the AssetManagerStore in Whitehall

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#274]
Once we've got all existing Organisation logos uploaded to Asset Manager, and we're serving Organisation logos from Asset Manager, we can update the `LogoUploader` to use the `asset_manager_storage` instead of the `asset_manager_and_quarantined_file_storage` so that these assets are only stored in Asset Manager and not on the Whitehall bit of the NFS mount.

## Dependencies

* Upload all existing logos from Whitehall to Asset Manager #276
* Update nginx config to serve organisation logos from Asset Manager #275
* Update Whitehall admin to redirect requests for Organisation logos to assets-origin #273

**Comment by chrisroos** [comment]
I'm going to take a look at this.

**Comment by floehopper** [comment]
@chrisroos: I hope you don't mind but I've expanded the description of this PR slightly:

> ... so that these assets are only stored in Asset Manager and not on the Whitehall bit of the NFS mount.

Please correct this if my understanding is incorrect.

**Comment by chrisroos** [comment]
I discovered issue #291 while working on this so am going to look at that first.

**Comment by chrisroos** [comment]
I think there _might_ be a problem with the synchronous call to `Services.asset_manager.whitehall_asset` in `Whitehall::AssetManagerStorage::File#url` once we switch to using the `AssetManagerStorage` only. I'm guessing this might be problematic if we request the url of an organisation logo before the logo has been uploaded to Asset Manager.

**Comment by chrislo** [comment]
We've opened https://github.com/alphagov/whitehall/pull/3532 to make this change - we'll want to check on integration after it is merged and deployed.

**Comment by chrislo** [comment]
https://github.com/alphagov/whitehall/pull/3532 has been merged.

**Comment by chrisroos** [comment]
We noticed a problem with replacing assets once we'd switched to using the `AssetManagerStorage` only. This was fixed in https://github.com/alphagov/whitehall/pull/3542 so I'm going to close this issue.
