### ISSUE TITLE
Create a report/dashboard to show our Asset Manager progress

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#284]
It'd be good if we can show, at a glance, our progress toward:

* Serving assets from S3
* Removing assets from NFS
* Migrating assets from Whitehall to Asset Manager

The [Assets Grafana dashboard](https://grafana.publishing.service.gov.uk/dashboard/db/assets?orgId=1) shows the disk usage of assets on NFS. We expect to see this number decrease (essentially to 0) as we move more assets to S3 and remove them from NFS. It _might_ be useful to break this number down so that it shows the number of assets stored for Whitehall vs Asset Manager.

It'd be good to find a way of showing the number of assets being served from Whitehall vs Asset Manager. The number of assets served by Whitehall should reduce to 0 while the number served by Asset Manager will increase by the same amount.

It'd be good to show something about the requests being handled by Asset Manager, along with the response times and error rates.

**Comment by chrisroos** [comment]
> It'd be good to find a way of showing the number of assets being served from Whitehall vs Asset Manager. The number of assets served by Whitehall should reduce to 0 while the number served by Asset Manager will increase by the same amount.

All Whitehall assets[1] are available on /government/uploads so it should be relatively easy to see the number of these requests being served by Whitehall vs Asset Manager in Kibana.

[1]: Apart from the special case Number 10 (see #268) and HMRC (see issue #217) assets.

**Comment by chrisroos** [comment]
I wonder whether the count of Whitehall assets in Asset Manager might be useful.

**Comment by chrisroos** [comment]
I've just tried to query Kibana to find /government/uploads assets served by Asset Manager. Unfortunately, the queries that I've used in the past (https://github.com/alphagov/asset-manager/issues/153#issuecomment-328506583) no longer seem to work...

**Comment by chrislo** [comment]
We [created a spreadsheet](https://docs.google.com/spreadsheets/d/11XxUJopMWw6QxPJGCTIwixHWh1FEm1iNEr3qSCZkYBg/edit#gid=0%0A) to show the progress in migrating assets from Whitehall to Asset Manager, and from NFS to S3.

We've completed the first row of the sheet for today `2017-11-15` and populated the columns using the following instructions.

Disk usage
==========

Columns `/mnt/uploads/asset-manager` and `/mnt/uploads/whitehall` are copied from the output of running the following command

``` bash
ssh asset-master-1.backend.integration 'du -d1 /mnt/uploads'
```

Asset Manager Whitehall requests / unique assets
================================================

Log in to [Kibana](https://kibana.logit.io) navigate to the Production instance and click on "Dev Tools" in the sidebar. Paste the following Elasticsearch query into the console and hit the "run" button to execute it.

``` javascript
GET _search
  {
    "size" : 0,
    "query": {
      "bool": {
        "must": [
          { "match": { "application" : "asset-manager" } },
          { "match": { "@fields.controller" : "whitehall_media" } },
          { "match": { "@fields.action" : "download" } },
          { "range" : { "@timestamp" : { "gte" : "now-7d/d" } } }
        ]
      }
    },
    "aggs" : {
      "distinct_paths" : {
        "cardinality" : {
          "field" : "@fields.path"
        }
      }
    }
  }
```

The output will look like

    {
      "took": 145,
      "timed_out": false,
      "_shards": {
        "total": 43,
        "successful": 43,
        "failed": 0
      },
      "hits": {
        "total": 1234,
        "max_score": 0,
        "hits": []
      },
      "aggregations": {
        "distinct_paths": {
          "value": 1234
        }
      }
    }

Where `hits > total` is the value to copy to the `Asset Manager Whitehall requests (last 7 days)` column in the sheet and `aggregations > distinct_paths > value` is the value for `Asset Manager Whitehall unique assets (last 7 days)`.

Mainstream requests / unique assets
===================================

Log in to [Kibana](https://kibana.logit.io) navigate to the Production instance and click on "Dev Tools" in the sidebar. Paste the following Elasticsearch query into the console and hit the "run" button to execute it.

``` javascript
GET _search
  {
    "size" : 0,
    "query": {
      "bool": {
        "must": [
          { "match": { "application" : "asset-manager" } },
          { "match": { "@fields.controller" : "media" } },
          { "match": { "@fields.action" : "download" } },
          { "range" : { "@timestamp" : { "gte" : "now-7d/d" } } }
        ]
      }
    },
    "aggs" : {
      "distinct_paths" : {
        "cardinality" : {
          "field" : "@fields.path"
        }
      }
    }
  }
```

Copy the values from the output to the sheet as above.

Whitehall requests / unique assets
==================================

Log in to [Kibana](https://kibana.logit.io) navigate to the Production instance and click on "Dev Tools" in the sidebar. Paste the following Elasticsearch query into the console and hit the "run" button to execute it.

``` javascript
GET _search
  {
    "size" : 0,
    "query": {
      "bool": {
        "must": [
          { "match": { "application" : "whitehall" } },
          { "match": { "controller" : "public_uploads" } },
          { "match": { "action" : "show" } },
          { "range" : { "@timestamp" : { "gte" : "now-7d/d" } } }
        ]
      }
    },
    "aggs" : {
      "distinct_paths" : {
        "cardinality" : {
          "field" : "path"
        }
      }
    }
  }
```

Copy the values from the output to the sheet as above.

**Comment by chrislo** [comment]
At the moment @chrisroos and I thought that manually following the above instructions every few days will give us enough sense of how things are progressing. We may want to set up a reminder to do so. 

I just spoke to @floehopper and we thought about adding a count of the number of assets in the Asset Manager S3 bucket (and possibly the total size) so we can track the migration.

**Comment by floehopper** [comment]
@chrisroos, @chrislo Would it also be worth capturing some measurement of 4xx/5xx HTTP response codes in case something we do causes this to rise...?

**Comment by floehopper** [comment]
I had a quick go at accessing the Cloudwatch statistics which are enabled by default on S3 buckets (`BucketSizeBytes` by storage class and `NumberOfObjects` aggregated for all storage classes). I had to give the user `cloudwatch:GetMetricStatistics` & `cloudwatch:ListMetrics` to *all* resources to make the following work using the AWS CLI: https://gist.github.com/floehopper/45ef153c8e4aac3b6363d3ab3ff177b0

I think we could probably do something similar using the AWS SDK from within the Asset Manager app: http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudWatch/Client.html#get_metric_statistics-instance_method

**Comment by chrisroos** [comment]
@floehopper and I have just been chatting about this and agreed that it'd be useful to include the number of assets (Whitehall, mainstream and deleted?) in the database.

**Comment by chrislo** [comment]
I counted the number of assets in the database by starting a `govuk_app_console asset-manager` on `backend-1.integration` and running

```
irb(main):001:0> WhitehallAsset.count
=> 24186
irb(main):002:0> Asset.count
=> 89103
irb(main):006:0> Asset.where(:deleted_at.ne => nil).count
=> 2619
```

**Comment by chrislo** [comment]
I'm going to close this issue as we've set the dashboard/report up and have a process in place for keeping it updated.
