### ISSUE TITLE
Delete orphan S3 objects

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#305]
From #301:

> There are approx 1137 objects on S3 whose uuid does not match any asset in the database. All of these S3 objects have a key of length 24 (e.g. 58cba21ee5274a16e8000030) rather than 36 (e.g. 00172d97-73b1-42dc-8c3e-7b90083f497b). We believe the former are a remnant from when we used the database ID vs a separate UUID as the S3 key. We think they can safely be deleted.

I think it's worth deleting these orphan S3 objects to avoid confusion in the future.

The key lengths can be obtained using the following command:

```
$ aws s3api list-objects-v2 --bucket govuk-assets-integration --query 'Contents[]' | jq 'map(.Key) | map(length) | unique'
[
  24,
  36
]
```

Counts of S3 objects with these key lengths can be obtained using the following commands:

```
$ aws s3api list-objects-v2 --bucket govuk-assets-integration --query 'length(Contents[?length(@.Key) == `24`])'
1137

$ aws s3api list-objects-v2 --bucket govuk-assets-integration --query 'length(Contents[?length(@.Key) == `36`])'
63950

$ aws s3api list-objects-v2 --bucket govuk-assets-integration --query 'length(Contents)'
65087
```

Some examples of the 24-character keys can be obtained using the following command:

```
$ aws s3api list-objects-v2 --bucket govuk-assets-integration --query 'Contents[?length(@.Key) == `24`].Key | [0:9]'
[
    "58cba21ee5274a16e8000030",
    "58cba5d040f0b67ec8000204",
    "58cbb24d40f0b62a0700002a",
    "58cbb2e440f0b62a0700002c",
    "58cbb364e5274a16e3000020",
    "58cbb3e940f0b67ec800020c",
    "5981afe040f0b61e48000037",
    "5981ea9340f0b61e4800003d",
    "59847aef40f0b61e4b000064"
]
```

**Comment by floehopper** [comment]
@chrisroos, @chrislo: The AWS IAM user for Asset Manager doesn't have `s3:DeleteObject` permission for the S3 bucket. Do you think we should add it (permanently via Terraform) or do you think a 2ndline person might have suitable credentials to allow objects to be deleted from the relevant bucket(s)?

**Comment by chrisroos** [comment]
I don't think we should add the `s3:DeleteObject` permission to the AWS IAM user for Asset Manager given that we're not expecting to need this permission in the general operation of the app. I think we should rely on 2ndline or infrastructure being able to run a script that cleans up the orphan assets for us.

**Comment by floehopper** [comment]
@chrisroos:

Thanks.

* Do you happen to know whether 2ndline users already have permission to delete objects from the Asset Manager S3 bucket in each environment?

* In the light of #311, I wonder whether we ought to give the Asset Manager IAM user permission to delete objects. What do you think...?

**Comment by floehopper** [comment]
Anyhoo, here's a couple of shell commands which will should do the trick if the right permissions are in place:

```
$ aws s3api list-objects-v2 --bucket govuk-assets-<environment> --query 'Contents[?length(@.Key) == `24`].[Key]' --output text >orphan-s3-object-keys.txt
$ cat orphan-s3-object-keys.txt | wc -l # => 1137
$ cat orphan-s3-object-keys.txt | xargs -I {} aws s3api delete-object --bucket govuk-assets-<environment> --key {}
```

The first command should take less than a minute to run. The last command should take a few minutes to run and its progress can be monitored by tailing the output file.

**Comment by floehopper** [comment]
I've opened https://github.com/alphagov/asset-manager/pull/312 to make the scripts available for someone with the appropriate AWS credentials to run.

**Comment by floehopper** [comment]
We've realised that two assets which have recently been permanently deleted will also have left behind orphan S3 objects with the following keys:

* "9883ea2d-995f-4418-9ca1-abf31b572fa4"
* "be8a0003-4b25-4047-8a5f-f7ddc3c52716"

We should delete these S3 objects at the same time as deleting the other orphan S3 objects.

**Comment by floehopper** [comment]
@boffbowsh has just run the following commands for us against the production AWS environment:

```
aws s3api list-objects-v2 --bucket govuk-assets-production --query 'Contents[?length(@.Key) == `24`].[Key]' --output text > orphan-s3-object-keys.txt
cat orphan-s3-object-keys.txt | wc -l
# ensure the result is 1137

cat orphan-s3-object-keys.txt | xargs -I {} aws s3api delete-object --bucket govuk-assets-production --key {} --output text > deleted-s3-objects.txt

aws s3api delete-object --bucket govuk-assets-production --key 9883ea2d-995f-4418-9ca1-abf31b572fa4 --output text >> deleted-s3-objects.txt
aws s3api delete-object --bucket govuk-assets-production --key be8a0003-4b25-4047-8a5f-f7ddc3c52716 --output text >> deleted-s3-objects.txt
```

The staging & integration S3 buckets will be fixed by the nightly sync. So we think we can close this issue.
