### ISSUE TITLE
Migrate all Whitehall non-attachment assets to Asset Manager

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#341]
This is a meta-issue to keep track of the migration of all of the assets in Whitehall to Asset Manager. The work is being handled in pieces under individual issues. 

## Assets under `system/uploads`

| Model                                  | Uploader                         | path                                                       | count   | total size |
|----------------------------------------|----------------------------------|------------------------------------------------------------|---------|------------|
| AttachmentData\#file                   | AttachmentUploader               | `system/uploads/attachment_data/file`                      | 1404672 | 520.6 GiB  |
|                                        |                                  | `system/uploads/attachment/file`                           | 6882    | 1.8 GiB    |
| ClassificationFeaturingImageData\#file | ImageUploader                    | `system/uploads/classification_featuring_image_data/file`  | 15498   | 2.0 GiB    |
| ConsultationResponseFormData\#file     | ConsultationResponseFormUploader | `system/uploads/consultation_response_form_data/file`      | 737     | 139.5 MiB  |
|                                        |                                  | `system/uploads/consultation_response_form/file`           | 19      | 4.3 MiB    |
| DefaultNewsOrganisationImageData\#file | ImageUploader                    | `system/uploads/default_news_organisation_image_data/file` | 1862    | 264.7 MiB  |
|                                        |                                  | `system/uploads/edition_organisation_image_data/file`      | 11402   | 1.4 GiB    |
|                                        |                                  | `system/uploads/edition_world_location_image_data/file`    | 5243    | 507.4 MiB  |
| Feature\#image                         | ImageUploader                    | `system/uploads/feature/image`                             | 473781  | 55.1 GiB   |
| ImageData\#file                        | ImageUploader                    | `system/uploads/image_data/file`                           | 494970  | 57.5 GiB   |
|                                        |                                  | `system/uploads/news_article/featuring_image`              | 10      | 4.1 MiB    |
|                                        |                                  | `system/uploads/news_article/image`                        | 112     | 31.5 MiB   |
| Organisation\#logo                     | LogoUploader                     | `system/uploads/organisation/logo`                         | 106     | 2.6 MiB    |
| Person\#image                          | ImageUploader                    | `system/uploads/person/image`                              | 23927   | 2.0 GiB    |
| PromotionalFeatureItem\#image          | ImageUploader                    | `system/uploads/promotional_feature_item/image`            | 371     | 12.8 MiB   |
| TakePartPage\#image                    | ImageUploader                    | `system/uploads/take_part_page/image`                      | 147     | 18.2 MiB   |
|                                        |                                  | `system/uploads/topical_event/logo`                        | 490     | 44.7 MiB   |

- ConsulationResponseFormUploader assets are being migrated in #297 
- LogoUploader assets were migrated in #276 
- LogoUploader assets are being deleted in #272 
- ImageUploader assets are being migrated in #215
- Assets which do not have an associated uploader are being migrated in #216

## Assets under `uploaded`

| Path                                   | Count | Size     |
|----------------------------------------|-------|----------|
| `./uploaded/hmrc`                      | 148   | 5.2 GiB  |
| `./uploaded/hmrc/paye-test`            | 3     | 11.7 KiB |
| `./uploaded/number10/garden.tiles`     | 307   | 23.5 MiB |
| `./uploaded/number10/image_001.tiles`  | 241   | 13.8 MiB |
| `./uploaded/number10/image_002.tiles`  | 241   | 13.7 MiB |
| `./uploaded/number10/image_003b.tiles` | 295   | 9.6 MiB  |
| `./uploaded/number10/image_004.tiles`  | 241   | 20.6 MiB |
| `./uploaded/number10/image_006.tiles`  | 241   | 23.5 MiB |
| `./uploaded/number10/image_007.tiles`  | 241   | 22.0 MiB |
| `./uploaded/number10/image_008.tiles`  | 241   | 16.7 MiB |
| `./uploaded/number10/image_011.tiles`  | 241   | 21.1 MiB |
| `./uploaded/number10/image_013.tiles`  | 295   | 14.0 MiB |
| `./uploaded/number10/image_014.tiles`  | 295   | 14.6 MiB |
| `./uploaded/number10/study.tiles`      | 307   | 14.8 MiB |

- Migration of these assets is captured in #216

## Assets under `./government/uploads/system/uploads/`

There's also 677 files under the following 4 sub-directories
-  `./government/uploads/system/uploads/attachment_data/file`
-  `./government/uploads/system/uploads/edition_organisation_image_data/file`
-  `./government/uploads/system/uploads/image_data/file`
-  `./government/uploads/system/uploads/person/image`

## Notes

We'll need to upload all existing Whitehall non-attachment assets which have models stored in the database before we can update the Nginx config to serve Whitehall images from Asset Manager (see issue #214). Note that there other Whitehall non-attachment assets which are served by the `PublicUploadsController` which do *not* have models stored in the database - these are captured in #216 & #217.

In order to avoid wholesale cache invalidation, we should set values for `legacy_etag` and `legacy_last_modifed` based on the underlying file in the "clean" directory when creating these Whitehall assets via the Asset Manager API as per [this PR](https://github.com/alphagov/asset-manager/pull/242) - see #234 for more details.

**Comment by floehopper** [comment]
I believe this is all done. @chrislo, @chrisroos please re-open if you disagree.
