### ISSUE TITLE
GdsApi::InvalidUrl exception when migrating assets

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#384]
https://sentry.io/govuk/app-whitehall/issues/429050852/

While running the task to migrate all assets under `system/uploads/feature/image` (Whitehall Feature images) (https://github.com/alphagov/asset-manager/issues/215) some `GdsApi::InvalidUrl` exceptions were raised with messages such as

```
URI must be ascii only "https://asset-manager.publishing.service.gov.uk/whitehall_assets//government/uploads/system/uploads/feature/image/58661/s960_MOU_\u53F0\u82F1\u5408\u4F5C\u5099\u5FD8\u9304\u7C3D\u7F72-960x640.jpg"
```

It appears that some of the file names under that directory are non-ascii.

There are 42 jobs that are failing which equates to 6 individual assets in 7 different generated versions. [An example of a publicly-available asset with a non-ascii URL](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/feature/image/58661/MOU_%E5%8F%B0%E8%8B%B1%E5%90%88%E4%BD%9C%E5%82%99%E5%BF%98%E9%8C%84%E7%B0%BD%E7%BD%B2-960x640.jpg). 

The full list of files is: 

- `system/uploads/feature/image/56493/Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s300_Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s630_Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s960_Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s216_Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s465_Diseño_sin_título.jpg`
- `system/uploads/feature/image/56493/s712_Diseño_sin_título.jpg`
- `system/uploads/feature/image/57540/Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s300_Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s630_Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s960_Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s216_Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s465_Ambasáda_web.jpg`
- `system/uploads/feature/image/57540/s712_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s300_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s630_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s960_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s216_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s465_Ambasáda_web.jpg`
- `system/uploads/feature/image/57541/s712_Ambasáda_web.jpg`
- `system/uploads/feature/image/58283/rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s300_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s630_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s960_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s216_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s465_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58283/s712_rsz_may_and_löfven.jpg`
- `system/uploads/feature/image/58657/MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s630_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s216_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s712_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s300_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s960_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58657/s465_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s630_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s216_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s712_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s300_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s960_MOU_台英合作備忘錄簽署-960x640.jpg`
- `system/uploads/feature/image/58661/s465_MOU_台英合作備忘錄簽署-960x640.jpg`

**Comment by floehopper** [comment]
@chrislo That sounds related to #371.

**Comment by chrisroos** [comment]
@chrislo and I have just chatted about this and agreed that we should fix this problem so that we can upload these existing assets to Asset Manager. I'm planning to investigate this in the next couple of days.

**Comment by chrisroos** [comment]
I've added this to the "Serve Whitehall non-attachment assets from Asset Manager" milestone as I think we'll need to fix the problem before we can close that milestone.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/gds-api-adapters/pull/794 to address this problem.

**Comment by chrisroos** [comment]
We'll need to bump the version of gds-api-adapters and then use that new version in Whitehall before we can consider this issue to be fixed.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/gds-api-adapters/pull/795 to bump the version of the gds-api-adapters Gem.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/whitehall/pull/3677 to use the latest version of gds-api-adapters in Whitehall.

**Comment by chrisroos** [comment]
Whitehall was upgraded to gds-api-adapters 50.9.1 in https://github.com/alphagov/whitehall/pull/3678.

**Comment by chrisroos** [comment]
Whitehall was deployed to staging and production this morning.

**Comment by chrisroos** [comment]
I've marked the associated issue in Sentry as resolved and am closing this issue given that we hope this is fixed.
