### ISSUE TITLE
Ensure Whitehall migrate_assets Rake task is resilient to application deployments

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#414]
We ran into this problem when trying to migrate Whitehall's images to Asset Manager (issue #404). We store an absolute path to the asset in the Sidekiq job. Because we're using Capistrano to deploy, this will be something like '/path/to/releases/\<timestamped-release-directory>'. If Whitehall is deployed while the jobs are being processed then they will start to fail because we can't determine the actual path to the asset. I thought we'd seen these sort of exceptions in Sentry but I can no longer find them so maybe they just caused the jobs to fail without raising an exception...

We probably want to do this before doing "Serve Whitehall's images from Asset Manager #404", unless we can guarantee that Whitehall won't be deployed while that migration is being run.

**Comment by chrislo** [comment]
The changes to the rake task are on production. I [tested interrupting a migration](https://github.com/alphagov/whitehall/pull/3693#issuecomment-358299055) on integration and it seems to have solved the problem. I'll close this issue when the code is on production.

**Comment by chrislo** [comment]
This has now been deployed to production.
