### ISSUE TITLE
Investigate use of JWT to access draft content

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#423]
The authenticating-proxy app, which is used in the draft stack, allows authentication using JWT. We believe this is used by publishing apps to allow access to draft documents for fact-checkers who have no Signon account. It would be useful to know which publishing apps do this - in particular does Whitehall do it?

**Comment by floehopper** [comment]
As far as I can see, the only publishing app which generates JWT tokens is Publisher. At the moment I assume that if any draft documents created by Publisher contain links to attachments, those links will be publicly accessible (although "secure" through obscurity).

At the moment the only assets which are protected when their parent documents are draft are Whitehall attachment assets.These are currently protected by SSO and associated logic in the Whitehall app.

So given that our current priority is to move Whitehall assets into Asset Manager, *for now*, we only need to replicate this SSO protection and not the JWT mechanism.

At some point, it might make sense to convert all publishing apps to mark assets as draft when appropriate, for them to all use JWT for fact-checking URLs, and to support all of this in Asset Manager. However, I don't think any of this is needed in order for us to move Whitehall attachment assets to Asset Manager.

@chrisroos, @danielroseman Does that make sense to you?

**Comment by danielroseman** [comment]
Yes that sounds right. There's no work planned to move Whitehall to use the draft stack with JWT for fact checking; currently Whitehall shows its own fact check previews that bypass SSO but do not include attachments.
