### ISSUE TITLE
Make draft-assets virtual host publicly accessible in staging & production

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#430]
You may need to do some/all of the following:

* Create SSL certificates for the new virtual host so it can support HTTPS
* Create DNS entries for the new virtual host so it is publicly accessible

**Comment by chrisroos** [comment]
I'm going to start investigating how we do this.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7202 to enable draft-assets in staging and production.

**Comment by chrisroos** [comment]
The changes in https://github.com/alphagov/govuk-puppet/pull/7202 were merged last week and became https://github.com/alphagov/govuk-puppet/releases/tag/release_19996. Release 20001 of puppet was deployed to staging and production at 13:02 yesterday so these changes should be ready to test.

**Comment by chrisroos** [comment]
I think this is working as expected in staging and production. I found the URL of a known asset (https://assets.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg) and requested it via `draft-assets` in both staging and production. I'm redirected to `/auth/gds` in both cases and I don't see any SSL errors:

```
$ curl https://draft-assets.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg
<html><body>You are being <a href="https://draft-assets.publishing.service.gov.uk/auth/gds">redirected</a>.</body></html>C

$ curl https://draft-assets.staging.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg
<html><body>You are being <a href="https://draft-assets.staging.publishing.service.gov.uk/auth/gds">redirected</a>.</body></html>
```

**Comment by chrisroos** [comment]
I think this is all done so I'm closing this issue.
