### ISSUE TITLE
Ensure all users have signin permission for Asset Manager app in Signon

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#434]
* Ensure Asset Manager app `signin` permission is automatically added to new users
* Add Asset Manager app `signin` permission to existing users

**Comment by floehopper** [comment]
@h-lame pointed me at [this commit in Signon][1] where he added a migration to make `signin` a default permission for Content Preview & Support apps and applied that permission to all existing users. We should probably do something very similar for Asset Manager.

[1]: https://github.com/alphagov/signon/pull/560/commits/45d3fffacbe94e627bab5799c182328cb3ae0783

**Comment by floehopper** [comment]
Until we split Asset Manager into frontend & backend apps (or at least two instances of the same app with different configs), we're going to need use the existing "Asset Manager" `Doorkeeper::Application` in the Signon app. This is because the `gds-sso` gem only supports authenticating against a single Signon app and the Asset Manager app is already using `gds-sso` to protect its API.

We are OK with this, because the API routes are not publicly accessible, even via the new `draft-assets` host. However, it might be worth considering changing Asset Manager so it checks that the authenticated user for API access matches ones of the Signon API users for one of the publishing apps.

**Comment by floehopper** [comment]
I've just opened https://github.com/alphagov/signon/pull/672 to address this.

**Comment by floehopper** [comment]
I'm going to hold off merging https://github.com/alphagov/signon/pull/672 until we've got the `draft-assets` host properly setup in staging & production, i.e. in https://github.com/alphagov/asset-manager/issues/430.

**Comment by chrisroos** [comment]
The `draft-assets` host is now accessible and working as expected in staging and production so I think we're OK to merge the changes in https://github.com/alphagov/signon/pull/672.

**Comment by floehopper** [comment]
I'm going to look at getting alphagov/signon#672 merged.

**Comment by floehopper** [comment]
After [some slight hiccups][1], this has now been deployed to integration, staging & production.

[1]: https://github.com/alphagov/signon/pull/672#issuecomment-364984146
