### ISSUE TITLE
Ensure Admin::EditionsHelper#attachment_virus_status works when asset is stored in Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#448]
See https://github.com/alphagov/whitehall/blob/468cfe3f8f78164c4d93048e9948086a1350cbbf/app/helpers/admin/editions_helper.rb#L230-L241

**Comment by chrislo** [comment]
Incorporated into #470 as it will be tackled during the switch to Asset Manager storage.
