### ISSUE TITLE
Redis::CommandErrorSidekiq/VirusScanWorker

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#461]
`OOM command not allowed when used memory > 'maxmemory'.`

We saw a number of [these exceptions in Sentry](https://sentry.io/govuk/app-asset-manager/issues/447725078/) on Fri 2 Feb.

**Comment by chrisroos** [comment]
I'm fairly confident these exceptions were caused when we tried to [migrate all Whitehall attachments to Asset Manager on Fri 2 Feb](https://github.com/alphagov/asset-manager/issues/441#issuecomment-362621754).

The exceptions were raised at the point the app tried to queue up a job to upload the assets to S3. The 37 exceptions in Sentry corresponds to the 37 assets in the `clean` state in the integration database (`> Asset.where(state: 'clean').count #=> 37`).

I think we'll need ask someone in 2ndline to queue up the jobs necessary to upload these assets to S3.

**Comment by thomasleese** [comment]
We've reduced the memory usage on Redis which should solve this.
