### ISSUE TITLE
Add relative link header to responses for Whitehall assets from Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#466]
In Whitehall the `AttachmentsController#show` action adds a `Link` response header for the parent document with the `rel='up'` qualifier. See https://github.com/alphagov/whitehall/blob/68f93f28ac1d40fedc9b49884ec30c599252cb71/app/controllers/attachments_controller.rb#L57-L61. We'll need to reproduce this for Whitehall assets served from Asset Manager and the value will need to be kept up-to-date like the draft status.

Note that we'll need to make changes so this working on both an ongoing basis and then doing it for all the existing assets. We might want to split this into two issues.

**Comment by chrisroos** [comment]
We can see an example of a `Link` header when requesting a Whitehall attachment in production:

```
$ curl -v https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/684819/March_2018_Consular_Fees.pdf > /dev/null

> GET /government/uploads/system/uploads/attachment_data/file/684819/March_2018_Consular_Fees.pdf HTTP/1.1
> Host: www.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Link: <https://www.gov.uk/government/publications/rwanda-consular-fees--2>; rel="up"
< <snipped>
```

**Comment by chrisroos** [comment]
The `Link` header was added in https://github.com/alphagov/whitehall/pull/2202. The description explains why:

> So that the cover sheet for an attachment is easily discoverable by crawlers and other clients, we should surface the attachment edition's public URL via HTTP headers.

**Comment by chrisroos** [comment]
I've started working on the changes to Whitehall in [WIP: Set parent_document_url when updating attachments](https://github.com/alphagov/whitehall/pull/3825).

**Comment by chrisroos** [comment]
I've started working on the changes to Asset Manager in [WIP: Add support for parent document URL to Asset Manager #502](https://github.com/alphagov/asset-manager/pull/502).

**Comment by chrisroos** [comment]
The changes in both Whitehall PR #3825 and Asset Manager PR #502 have been deployed to integration.

I tested that this was working as expected in integration by:

1. Create a consultation
2. Attach a file to the consultation
3. Observe that the asset in Asset Manager doesn't have the `parent_document_url` set
4. Force publish the consultation
5. Observe that the asset in Asset Manager has its `parent_document_url` set to the URL of the document

**Comment by chrisroos** [comment]
The changes in both https://github.com/alphagov/whitehall/pull/3825 and https://github.com/alphagov/asset-manager/pull/502 have now been deployed to staging and production.

I've confirmed that the behaviour is working as expected in staging by:

1. Create a consultation
2. Add an attachment to the consultation
3. Force publish the consultation
4. Request the attachment using www-origin (this routes the request to Whitehall) and observe that the `Link` header is being set to the URL of the edition
5. Request the attachment using draft-assets (this routes the request to Asset Manager) and observe that the `Link` header is being set to the URL of the edition.

We still need to update the parent document URL of all the attachments in Asset Manager but that's captured in issue #513.

I think this is all done so I'm closing this issue.
