### ISSUE TITLE
Ensure PDF attachment thumbnail works with Asset Manager storage

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#468]
I think this should "just work" when we switch over the storage for the `AttachmentUploader` to `Whitehall::AssetManagerStorage`, but we should check that this is really the case. Ultimately we might want to move the thumbnail-ing process into Asset Manager, but that's a separate issue.

**Comment by chrislo** [comment]
Incorporated into #470 as it will be tackled during the switch to Asset Manager storage.
