### ISSUE TITLE
Set appropriate Cache-Control header for Whitehall assets when user is signed in

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#494]
It looks as if Whitehall attachments are currently being served [with a `Cache-Control` header of `no-cache`][1] if the user is signed in. I assume this is meant to be used to ensure that editors see the most up-to-date version of an attachment.

I have a feeling this behaviour might've been present for non-attachments in Whitehall in the old `PublicUploadsController`. It would be worth checking in order to inform the decision of how/whether to implement equivalent behaviour in Asset Manager.

It's not immediately obvious to me whether we should do something similar in Asset Manager, because I'm not entirely sure the fact that the `current_user` is set in Asset Manager is semantically equivalent to `current_user` in Whitehall.

[1]: https://github.com/alphagov/whitehall/blob/master/app/controllers/attachments_controller.rb#L79

**Comment by chrisroos** [comment]
@chrislo and I have opened https://github.com/alphagov/asset-manager/pull/517 to update the caching behaviour in Asset Manager.

**Comment by chrisroos** [comment]
I'm going to test that this is working as expected.

**Comment by chrisroos** [comment]
I've tested this in production by requesting the same image from `assets-origin` and from `draft-assets`:

* https://assets-origin.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg
* https://draft-assets.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg

I used the Chrome Developer tools to inspect the Response headers and have confirmed that the `Cache-Control` header is set to `max-age=86400, public` when requested from `assets-origin` and is set to `no-cache` when requested from `draft-assets`.

I'm happy that this is working as expected so I'm closing this issue.
