### ISSUE TITLE
Make CSV preview of Whitehall attachments work when they are moved to Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#495]
The `AttachmentsController#preview` action in Whitehall is used to preview CSV files. It currently does this by creating an instance of `CsvPreview` and passing this to the view. 

`CsvPreview` reads the CSV file from disk and formats a subset of the file for display to the end user. 

For example [this guidance page](https://www.gov.uk/government/statistics/insolvency-statistics-october-to-december-2017) has a link to a "view online" version of a CSV

<img width="688" alt="screen shot 2018-02-27 at 09 14 31" src="https://user-images.githubusercontent.com/16707/36733475-c09ee59e-1b9e-11e8-911a-7ad2263540bb.png">

Which links to [a page](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/675936/Q4_2017_csv.csv/preview) with a truncated version of the CSV rendered as HTML

<img width="1035" alt="screen shot 2018-02-27 at 09 16 11" src="https://user-images.githubusercontent.com/16707/36733538-e9d85a76-1b9e-11e8-9392-a2be32fe3a77.png">

Before we can serve all attachments from Asset Manager we'll need to change the implementation of this feature. I think the best approach is to extract a new CSV preview controller from the existing AttachmentsController and modify `CsvPreview` to load the file from Asset Manager rather than from disk.

**Comment by chrislo** [comment]
There's currently 

```
Asset.where(file: /\.csv$/).count
=> 35047
```

csv files stored in Asset Manager in integration. 90% of them have a size less than 300KiB but the largest is 194MiB. 

I think this rules out fetching the entire file from Asset Manager into Whitehall before generating the preview.

**Comment by chrislo** [comment]
The 10 largest CSV files are

```
| /government/uploads/system/uploads/attachment_data/file/453752/2014-15_All_NHS_Trust_Accounts_data.csv                                      |  46341574 |
| /government/uploads/system/uploads/attachment_data/file/314512/FEC424_201213_FEChoices_Organisations_CourseLevel_SuccessRates.csv           |  63936327 |
| /government/uploads/system/uploads/attachment_data/file/399850/mappings-2015-01-27T10_26_13_00_00.csv                                       | 204208786 |
| /government/uploads/system/uploads/attachment_data/file/305557/ES_National_Data.csv                                                         | 113051688 |
| /government/uploads/system/uploads/attachment_data/file/245855/HMT_-_2011_Air_Data.csv                                                      | 105261565 |
| /government/uploads/system/uploads/attachment_data/file/509950/Datav1.csv                                                                   |  92306051 |
| /government/uploads/system/uploads/attachment_data/file/623040/legal-aid-statistics-provider-area-data-2016-17.csv                          | 172209742 |
| /government/uploads/system/uploads/attachment_data/file/626057/legal-aid-statistics-provider-and-area-data-2016-2017.csv                    | 169286913 |
| /government/uploads/system/uploads/attachment_data/file/623037/Legal_aid_statistics_in_England_and_Wales_provider_and_area_data_2016-17.csv | 172209742 |
| /government/uploads/system/uploads/attachment_data/file/603201/Postcode_level_gas_estimates_2015_experimental.csv                           |  50629248 |
```

**Comment by chrislo** [comment]
This has been deployed to production.
