### ISSUE TITLE
Fix setting of draft status for Whitehall attachment assets in Asset Manager

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#514]
Currently I think there is a flaw in the logic in `AttachmentDraftStatusUpdater`, because `AttachmentVisibility#visible?` can return `false` for a number of reasons, not just the fact that the attachment is "draft", e.g. it will do so if the attachment is deleted. We need to fix this logic.

**Comment by floehopper** [comment]
This should have been addressed in https://github.com/alphagov/whitehall/pull/3851, specifically in https://github.com/alphagov/whitehall/commit/816130588bd0c8593970a9ddf8a2939832ebcc93.

**Comment by chrisroos** [comment]
Although we've not tested this on integration/staging (because we can't see an easy way of doing so), we're confident in the automated tests that have been added so we're marking this as closed
