### ISSUE TITLE
NoMethodError in AssetManagerCreateWhitehallAssetWorker

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#522]
[This exception][1] has occurred a number of times in production.

When an attachment is added to a (consultation) `Response`,  `Admin::AttachmentsController#build_file_attachment` sets `AttachmentData#attachable` to the `Response`. Then `Whitehall::AssetManagerStorage#store!` passes the class and ID of the `Response` instance to the worker. Then in the worker, `PayloadBuilder::AccessLimitation.for` tries to call `#publicly_visible?` on instance of the `Response`, but the method isn't implemented, resulting in a `NoMethodError`.

I believe this will have prevented assets being created in Asset Manager for attachments on (consultation) `Response` objects. Thus once this problem is fixed, we'll need to ensure that any that have been missed are created, either by the failed jobs being re-tried or some other means.

[1]: https://sentry.io/govuk/app-whitehall/issues/490263226/

**Comment by floehopper** [comment]
It looks as if [this commit][1] in https://github.com/alphagov/whitehall/pull/3850 may have gone some way towards fixing this, because it introduces a `Response#publicly_visible?` method. However, when I try to reproduce the scenario locally, I still see an exception, albeit a different one:

```
NoMethodError: undefined method `organisations' for #<ConsultationOutcome:0x00007fd5e0d703a8>
    /Users/jamesmead/Code/alphagov/whitehall/.bundle/gems/gems/activemodel-5.0.6/lib/active_model/attribute_methods.rb:433:in `method_missing'
    /Users/jamesmead/Code/alphagov/whitehall/app/presenters/publishing_api/payload_builder/access_limitation.rb:6:in `for'
    /Users/jamesmead/Code/alphagov/whitehall/lib/asset_manager_access_limitation.rb:3:in `for'
    /Users/jamesmead/Code/alphagov/whitehall/app/workers/asset_manager_create_whitehall_asset_worker.rb:13:in `perform'
```

This is because there is no `Response#organisations` method. I'm continuing to investigate.

[1]: https://github.com/alphagov/whitehall/commit/259f74ce899008d8569f937c40fb0b9cb93ad63b

**Comment by floehopper** [comment]
I've come up with a naïve fix in https://github.com/alphagov/whitehall/pull/3863.

**Comment by chrisroos** [comment]
I just dug into this a bit because I wanted to understand why we've only seen these exceptions since Monday. My main concern was that prior to Monday's deploy we weren't creating assets for Responses in Asset Manager.

I traced the problem to https://github.com/alphagov/whitehall/commit/ac2770f18f80922b568669dec5ec7b30d67ecd88 in https://github.com/alphagov/whitehall/pull/3767 (my bad!). Prior to that commit we were using the `#access_limited_object` method to get the object that knew about access limiting (which was the parent `Consultation` in the case of a `Response`). After that commit we were asking the `Response` directly. So, I'm confident that the fact we've only seen these exceptions since Monday is because it's not particularly common to upload a `Response` to an access-limited `Consultation`.

**Comment by floehopper** [comment]
@chrisroos Thanks for digging into this.

**Comment by floehopper** [comment]
I've just tried to reproduce the problem in integration as follows:

1. Create a consultation
2. Add a public feedback to the consultation
3. Add an attachment to the public feedback
4. Mark the consultation as access-limited
5. Save the consultation
6. Preview the consultation
7. Preview the attachment on the public feedback
8. Check Sentry for `NoMethodError` exceptions in `AssetManagerCreateWhitehallAssetWorker`

I didn't see any such exception and so I'm reasonably confident that the problem has been fixed by https://github.com/alphagov/whitehall/pull/3863.

**Comment by floehopper** [comment]
As far as I can see from Sentry the exception has never happened in the `integration-blue-aws` environment and so there will not have been any failed job on the queue to retry.

**Comment by floehopper** [comment]
Now that https://github.com/alphagov/whitehall/pull/3863 has been deployed to staging & production, I'm going to check I can't generate the exception on production.

**Comment by floehopper** [comment]
It looks as if [all 12 of the occurrences of the exception in staging][1] relate to a single file:

* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15881626026/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15881679541/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15881726391/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15881824254/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15881979983/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15882393639/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15883048152/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15884450389/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15886673239/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15890526705/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15896011108/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt
* https://sentry.io/govuk/app-whitehall/issues/495181114/events/15903529832/
  * /government/uploads/system/uploads/attachment_data/file/690535/20180315T173752Z.txt

It looks as if that file was a one used by @chrisroos for testing which explains why I can't find the parent consultation - I assume it's been over-written by the nightly environment sync. I guess that might mean that the job will keep trying to create the asset, but will keep failing probably on [this line][2] when it tries to lookup the (consultation) `Response` and it can't find it -> `ActiveRecord::RecordNotFound` exception.
  
[1]: https://sentry.io/govuk/app-whitehall/issues/495181114/events/
[2]: https://github.com/alphagov/whitehall/blob/97cbb1f54aad82b9009705c40dc64e43762db43c/app/workers/asset_manager_create_whitehall_asset_worker.rb#L10

**Comment by floehopper** [comment]
I can't see any `ActiveRecord::RecordNotFound` exceptions in staging, but I guess the exponential retry back-off might be quite big intervals now and so perhaps it won't happen for a while. In any case, I think we can probably just add comments to such exceptions and live with it until the retry mechanism gives up.

**Comment by floehopper** [comment]
There have been [26 occurrences of the exception in production][1], 13 for a single PDF and 13 for its thumbnail:

* `/government/uploads/system/uploads/attachment_data/file/689236/Business_rates_revaluations.pdf`
* `/government/uploads/system/uploads/attachment_data/file/689236/thumbnail_Business_rates_revaluations.pdf.png`

[1]: https://sentry.io/govuk/app-whitehall/issues/490263226/events/

**Comment by floehopper** [comment]
The production attachment and its thumbnail mentioned above are available on [this consultation][1].

* PDF: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/689236/Business_rates_revaluations.pdf
* Thumbnail: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/689236/Business_rates_revaluations.pdf

[1]: https://www.gov.uk/government/consultations/business-rates-delivering-more-frequent-revaluations

**Comment by floehopper** [comment]
Somehow the 2 jobs in production seem to have retried successfully on the 13th attempt ont Tue, 13 Mar 2018 at about 13:16 - 13:17. We can see the 2 assets exist in Asset Manager in integration (where they will've been copied by the overnight sync):

```
irb> a = WhitehallAsset.find_by(legacy_url_path: "/government/uploads/system/uploads/attachment_data/file/689236/Business_rates_revaluations.pdf")
irb> a.created_at
=> Tue, 13 Mar 2018 13:17:26 UTC +00:00
irb> a.state
=> "uploaded"
irb> a.draft?
=> true
irb> a.access_limited.size
=> 84
irb> a.legacy_url_path
=> "/government/uploads/system/uploads/attachment_data/file/689236/Business_rates_revaluations.pdf"
```

```
irb> a = WhitehallAsset.find_by(legacy_url_path: "/government/uploads/system/uploads/attachment_data/file/689236/thumbnail_Business_rates_revaluations.pdf.png")
irb> a.created_at
=> Tue, 13 Mar 2018 13:16:55 UTC +00:00
irb> a.state
=> "uploaded"
irb> a.draft?
=> true
irb> a.access_limited.size
=> 84
irb> a.legacy_url_path
=> "/government/uploads/system/uploads/attachment_data/file/689236/thumbnail_Business_rates_revaluations.pdf.png"
```

We can see that both of them are marked as access-limited which explains why I can't access them via `draft-assets`. Thus I'm happy to mark these exceptions as resolved.
