### ISSUE TITLE
Stop CsvPreviewController depending on attachment file existing on the filesystem

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#532]
The plan is to refactor `CsvPreviewController` so that it relies on response codes from the request made by `CsvFileFromPublicHost` to determine the virus-scan state of the attachment rather than the file on the filesystem. This should mean we'll be able to switchover to `AssetManagerStorage` seamlessly.

See https://github.com/alphagov/whitehall/pull/3811, and more specifically https://github.com/alphagov/whitehall/commit/db1e1636885308e64905d4a663d9670c0f50d1d2, for details.

**Comment by floehopper** [comment]
I've opened https://github.com/alphagov/whitehall/pull/3911 to address this, although it needs a little more work.

**Comment by chrislo** [comment]
https://github.com/alphagov/whitehall/pull/3911 has been tested, merged and deployed to all environments.
