### ISSUE TITLE
Consider using delayed-plugins-airbrake or airbrake/delayed_job

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#68]
Currently it looks as if the app is using explicit calls to `Airbrake.notify_or_ignore` to report exceptions to Errbit. I suspect we could reduce duplication and have this happen automatically by using either [`delayed-plugins-airbrake`](https://github.com/benjaminoakes/delayed-plugins-airbrake) (which I think only works with Airbrake <= v4, i.e. the current version) or [`airbrake/delayed_job`](https://github.com/airbrake/airbrake#delayedjob) (which is built into Airbrake >= v5, but would require us upgrading Airbrake within the app).

Before doing anything it would be worth checking what's being used elsewhere for Airbrake in apps running DelayedJob.

**Comment by floehopper** [comment]
This would be rendered moot if we [use Sidekiq instead of Delayed Job](https://github.com/alphagov/asset-manager/issues/179).

**Comment by chrislo** [comment]
We switched to sidekiq in #179 so this issue is no longer relevant.
