### ISSUE TITLE
Use S3 for storing and serving assets

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#76]
Things we need to do to get it working end-to-end: 

 - [x] Merge [changes to Asset Manager](https://github.com/alphagov/asset-manager/pull/74)
 - [x] Deploy Asset Manager changes to integration
 - [x] Deploy Asset Manager changes to staging and production
 - [x] Merge [changes to Terraform](https://github.com/alphagov/govuk-terraform-provisioning/pull/125)
 - [x] Deploy Terraform changes
 - [x] Store the IAM credentials generated in the deployment repository
 - [x] Deploy the IAM credentials 
 - [x] Merge [changes to puppet](https://github.com/alphagov/govuk-puppet/pull/6137)
 - [x] Deploy puppet changes
 - [x] (Deploy with hard restart of `asset-manager` - we think we need to do this so that the asset manager picks up the new environment variables)

**Comment by chrisroos** [comment]
I've just merged the changes in https://github.com/alphagov/govuk-puppet/pull/6137 which will set the AWS environment variables required by Asset Manager.

**Comment by chrisroos** [comment]
Leena deployed release_18998 of govuk-puppet to staging and production earlier today. This release contains the commit to set the AWS environment variables.

**Comment by chrisroos** [comment]
The deployed version of Asset Manager is quite a few commits behind master (https://github.com/alphagov/asset-manager/compare/deployed-to-production...master). I plan to get this deployed early next week.

**Comment by chrisroos** [comment]
We deployed Asset Manager to staging and production yesterday so it now includes the functionality for uploading assets to/optionally serving assets from S3.

**Comment by chrisroos** [comment]
I've merged the changes in https://github.com/alphagov/govuk-terraform-provisioning/pull/125 to create the AWS resources required by Asset Manager. I'm going to investigate getting them deployed.

**Comment by floehopper** [comment]
@chrislo confirmed that uploading an asset and downloading it with the `stream_from_s3` query string parameter was working OK in staging and production earlier today, so I'm going to close this issue.
