### ISSUE TITLE
Requests to stream assets from S3 can result in an empty 200 response

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#78]
I found it confusing that a request to serve an asset from S3 results in an empty 200 response if the `AWS_S3_BUCKET_NAME` environment variable isn't set. I think I'd prefer it to fail fast if I'm requesting a file from S3 when the app doesn't have enough information to be able to satisfy that request.

**Comment by floehopper** [comment]
This has been addressed in #84.
