### ISSUE TITLE
Upgrade Rails to 5.1

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#80]
Rails 5.1 appears to be the latest version being used for GOV.UK apps.

We should update the [Ruby/Rails versions spreadsheet](https://docs.google.com/spreadsheets/d/1FJmr39c9eXgpA-qHUU6GAbbJrnenc0P7JcyY2NB9PgU/edit#gid=1480786499) when we're done.

**Comment by floehopper** [comment]
I'm not sure there's a good reason not to upgrade to the latest 5.x version (which might be > v5.1 by the time we work on this), is there?

**Comment by chrisroos** [comment]
Asset Manager was upgraded to Rails 5.1.4 in https://github.com/alphagov/asset-manager/pull/298 so I'm closing this issue.
