### ISSUE TITLE
Upgrade CarrierWave

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#86]
The app is currently using v0.10.0 and the latest version is v1.1.0. It would be sensible to upgrade.

**Comment by floehopper** [comment]
See also #65.

**Comment by floehopper** [comment]
It looks as if Whitehall's carrierwave was upgraded in https://github.com/alphagov/whitehall/pull/3273. Given that we're hoping to move Whitehall asset management over to Asset Manager, I think this probably bumps up the priority to upgrade carrierwave within Asset Manager.

**Comment by chrisroos** [comment]
Carrierwave was upgraded from 0.10 to 0.11.2 in https://github.com/alphagov/asset-manager/pull/351 but I don't know of any reason for us not to upgrade further so I'm leaving this issue open.

**Comment by chrisroos** [comment]
We've just discovered that CarrierWave 1.0.0 and above allow non-ascii characters in filenames by default (see https://github.com/carrierwaveuploader/carrierwave/pull/1772 and [the CHANGELOG](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#100beta---2016-09-08) for more info).

At the moment (with CarrierWave 0.11.2) a file named "filé.txt" will be sanitized to "fil_.txt" in the database and on the filesystem. Upgrading to CarrierWave > 1.0.0 will mean that this file will continue to be named "filé.txt" in the database and on the filesystem.
