### ISSUE TITLE
Use rubocop-rspec

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#92]
Probably [via govuk-lint](https://github.com/alphagov/govuk-lint/issues/80), but possibly directly.

This would be a better fix for the `Metrics/BlockLength` rubocop problem than [this commit](https://github.com/alphagov/asset-manager/commit/9cb3ba39e9613ac3a0302a8a760275985b99bae2).

**Comment by floehopper** [comment]
I've added `rubocop-rspec` as a dependency to `govuk-lint` in alphagov/govuk-lint#83. However, note that doing so doesn't fix the `Metrics/BlockLength` problem as I had hoped. However, @h-lame has opened alphagov/govuk-lint#82 with an alternative fix for this which we should adopt.

As part of this investigation, I've done some work locally on auto-correcting violations in the `rubocop-rspec` cops. I'll open those changes as a separate PR once a new version of `govuk-lint` is available.

**Comment by chrisroos** [comment]
The `rubocop-rspec` gem was added in PR #192. @floehopper: Can this issue be closed?

**Comment by floehopper** [comment]
@chrisroos:

> Can this issue be closed?

Yes, I think so.
