### ISSUE TITLE
Asset Manager should generate IDs of objects stored on S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#94]
The objects we write to S3 are currently named using the BSON ID of the corresponding record in the Asset Manager database. We want to decouple the storage of the assets from the storage of their metadata in Mongo. We should generate our own IDs and use those to write the files to S3.

**Comment by floehopper** [comment]
We're now actively investigating [an alternative approach](https://github.com/alphagov/asset-manager/milestone/4). Closing.

**Comment by chrisroos** [comment]
We think this is going to be useful irrespective of whether we're redirecting to the assets, or serving them via an nginx proxy. Reopening.
