### ISSUE TITLE
Investigate whether it's possible to create redirects on S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#97]
We're hoping to redirect from the Asset Manager to a public asset on S3. If an asset is updated then we think we'll want to add a redirect from the old to new URLs.

**Comment by floehopper** [comment]
It is possible to get an S3 object URL to respond with a 301 (temporary) redirect by setting the `x-amz-website-redirect-location` property in the object's metadata. You can redirect to another object in the bucket by setting this property to the new object key, or you can redirect to an arbitrary URL by setting the property to the new URL. See the ["Configuring a Webpage Redirect" documentation][1].

[1]: http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by floehopper** [comment]
If you configure an S3 bucket for "static website hosting" then you can setup [more sophisticated routing rules][1], but I think that means we'd have to have an index page, so it's probably not going to be what we want.

[1]: http://docs.aws.amazon.com/AmazonS3/latest/dev/HowDoIWebsiteConfiguration.html#configure-bucket-as-website-routing-rule-syntax

**Comment by floehopper** [comment]
> It is possible to get an S3 object URL to respond with a 301 (temporary) redirect by setting the `x-amz-website-redirect-location` property in the object's metadata. You can redirect to another object in the bucket by setting this property to the new object key, or you can redirect to an arbitrary URL by setting the property to the new URL. See the ["Configuring a Webpage Redirect" documentation][1].

I've just been trying out the "301 redirect" mechanism and it seems to only work if you enable "static website hosting" for the S3 bucket which I'm not sure we want to do.

[1]: http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by floehopper** [comment]
I think these investigation tasks are "done", although we will need to decide how/whether we're going to handle updating assets. I plan to create a new issue or two to capture that.
