### ISSUE TITLE
Investigate whether we can remove the Access Control functionality from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#99]
There's functionality in the Asset Manager to limit access to assets based on the state of `Asset#access_limited?`. We're not sure whether this is being used. If it's not then we should remove the functionality.

**Comment by floehopper** [comment]
This may be related to [Consider fixing or removing the private Asset Manager host alias & associated functionality](https://github.com/alphagov/asset-manager/issues/156).

**Comment by chrisroos** [comment]
This is essentially a duplicate of issue #156 so I'm closing this one.
